// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("ProfileVideoAssessmentScore")]
    public partial class ProfileVideoAssessmentScore
    {
        public ProfileVideoAssessmentScore()
        {
            ProfileVideoAssessmentAnswerScores = new HashSet<ProfileVideoAssessmentAnswerScore>();
            ProfileVideoAssessmentCriteriaScores = new HashSet<ProfileVideoAssessmentCriteriaScore>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("ProfileID")]
        public int ProfileId { get; set; }
        [Column("VideoAssessmentID")]
        public int VideoAssessmentId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Score { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        public int Order { get; set; }
        public bool IsFailed { get; set; }
        public bool IsCompleted { get; set; }
        public string EvaluationComment { get; set; }

        [ForeignKey(nameof(ProfileId))]
        [InverseProperty("ProfileVideoAssessmentScores")]
        public virtual Profile Profile { get; set; }
        [ForeignKey(nameof(VideoAssessmentId))]
        [InverseProperty("ProfileVideoAssessmentScores")]
        public virtual VideoAssessment VideoAssessment { get; set; }
        [InverseProperty(nameof(ProfileVideoAssessmentAnswerScore.ProfileVideoAssessmentScore))]
        public virtual ICollection<ProfileVideoAssessmentAnswerScore> ProfileVideoAssessmentAnswerScores { get; set; }
        [InverseProperty(nameof(ProfileVideoAssessmentCriteriaScore.ProfileVideoAssessmentScore))]
        public virtual ICollection<ProfileVideoAssessmentCriteriaScore> ProfileVideoAssessmentCriteriaScores { get; set; }
    }
}