// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("ProfileMembership")]
    public partial class ProfileMembership
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("ProfileID")]
        public int ProfileId { get; set; }
        [Column("OrganizationID")]
        public int OrganizationId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Date { get; set; }
        [Required]
        [StringLength(500)]
        public string Role { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }

        [ForeignKey(nameof(OrganizationId))]
        [InverseProperty(nameof(GlpOrganization.ProfileMemberships))]
        public virtual GlpOrganization Organization { get; set; }
        [ForeignKey(nameof(ProfileId))]
        [InverseProperty("ProfileMemberships")]
        public virtual Profile Profile { get; set; }
    }
}