// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("Profile_Interest")]
    public partial class ProfileInterest
    {
        [Key]
        [Column("ProfileID")]
        public int ProfileId { get; set; }
        [Key]
        [Column("ID")]
        public int Id { get; set; }

        [ForeignKey(nameof(Id))]
        [InverseProperty(nameof(LookupItem.ProfileInterests))]
        public virtual LookupItem IdNavigation { get; set; }
        [ForeignKey(nameof(ProfileId))]
        [InverseProperty("ProfileInterests")]
        public virtual Profile Profile { get; set; }
    }
}