// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("ProfileQuestionItemScore")]
    public partial class ProfileQuestionItemScore
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("ProfileID")]
        public int ProfileId { get; set; }
        [Column("QuestionItemID")]
        public int QuestionItemId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Score { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        public int Order { get; set; }
        [Column("AnswerID")]
        public int? AnswerId { get; set; }
        [Column("AssessmentToolID")]
        public int AssessmentToolId { get; set; }
        public int? TimeAnswered { get; set; }

        [ForeignKey(nameof(AnswerId))]
        [InverseProperty(nameof(Qanswer.ProfileQuestionItemScores))]
        public virtual Qanswer Answer { get; set; }
        [ForeignKey(nameof(AssessmentToolId))]
        [InverseProperty("ProfileQuestionItemScores")]
        public virtual AssessmentTool AssessmentTool { get; set; }
        [ForeignKey(nameof(ProfileId))]
        [InverseProperty("ProfileQuestionItemScores")]
        public virtual Profile Profile { get; set; }
        [ForeignKey(nameof(QuestionItemId))]
        [InverseProperty("ProfileQuestionItemScores")]
        public virtual QuestionItem QuestionItem { get; set; }
    }
}