// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("ProfileEducationFieldOfStudy")]
    public partial class ProfileEducationFieldOfStudy
    {
        public ProfileEducationFieldOfStudy()
        {
            ProfileEducations = new HashSet<ProfileEducation>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("TitleEN")]
        public string TitleEn { get; set; }
        [Column("TitleAR")]
        public string TitleAr { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }

        [InverseProperty(nameof(ProfileEducation.FieldOfStudyNavigation))]
        public virtual ICollection<ProfileEducation> ProfileEducations { get; set; }
    }
}