// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("ProfileFactorScore")]
    public partial class ProfileFactorScore
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("ProfileID")]
        public int ProfileId { get; set; }
        [Column("FactorID")]
        public int FactorId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Score { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        public int Order { get; set; }
        [Column(TypeName = "decimal(20, 10)")]
        public decimal? StandardScore { get; set; }
        [Column("TScore", TypeName = "decimal(20, 10)")]
        public decimal? Tscore { get; set; }
        [Column("STENScore", TypeName = "decimal(20, 10)")]
        public decimal? Stenscore { get; set; }
        [Column(TypeName = "decimal(20, 10)")]
        public decimal? PercentileScore { get; set; }
        [Required]
        public bool? IsCompleted { get; set; }

        [ForeignKey(nameof(FactorId))]
        [InverseProperty("ProfileFactorScores")]
        public virtual Factor Factor { get; set; }
        [ForeignKey(nameof(ProfileId))]
        [InverseProperty("ProfileFactorScores")]
        public virtual Profile Profile { get; set; }
    }
}