// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("Profile_Meetups")]
    public partial class ProfileMeetup
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("MeetupID")]
        public int MeetupId { get; set; }
        [Column("ProfileID")]
        public int ProfileId { get; set; }
        [Column("MeetupStatusItemID")]
        public int MeetupStatusItemId { get; set; }

        [ForeignKey(nameof(MeetupId))]
        [InverseProperty("ProfileMeetups")]
        public virtual Meetup Meetup { get; set; }
        [ForeignKey(nameof(MeetupStatusItemId))]
        [InverseProperty(nameof(LookupItem.ProfileMeetups))]
        public virtual LookupItem MeetupStatusItem { get; set; }
        [ForeignKey(nameof(ProfileId))]
        [InverseProperty("ProfileMeetups")]
        public virtual Profile Profile { get; set; }
    }
}