// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("ProfilePillarScore")]
    public partial class ProfilePillarScore
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column("ProfileID")]
        public int ProfileId { get; set; }
        [Column("PillarID")]
        public int PillarId { get; set; }
        [Column("AssessmenttoolID")]
        public int AssessmenttoolId { get; set; }
        [Column(TypeName = "decimal(20, 10)")]
        public decimal? StandardScore { get; set; }
        [Column("TScore", TypeName = "decimal(20, 10)")]
        public decimal? Tscore { get; set; }
        [Column("STENScore", TypeName = "decimal(20, 10)")]
        public decimal? Stenscore { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Score { get; set; }
        public bool? IsCompleted { get; set; }
        public int Order { get; set; }
        [Column(TypeName = "decimal(20, 10)")]
        public decimal? Mean { get; set; }
        [Column(TypeName = "decimal(20, 10)")]
        public decimal? StandardDeviation { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? RecalculatedDatetime { get; set; }

        [ForeignKey(nameof(AssessmenttoolId))]
        [InverseProperty(nameof(AssessmentTool.ProfilePillarScores))]
        public virtual AssessmentTool Assessmenttool { get; set; }
        [ForeignKey(nameof(PillarId))]
        [InverseProperty("ProfilePillarScores")]
        public virtual Pillar Pillar { get; set; }
        [ForeignKey(nameof(ProfileId))]
        [InverseProperty("ProfilePillarScores")]
        public virtual Profile Profile { get; set; }
    }
}