// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("ProfileWorkExperience")]
    public partial class ProfileWorkExperience
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("ProfileID")]
        public int ProfileId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateFrom { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DateTo { get; set; }
        [Column("OrganizationID")]
        public int OrganizationId { get; set; }
        [Column("IndustryID")]
        public int IndustryId { get; set; }
        [Column("CountryID")]
        public int CountryId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Required]
        [StringLength(300)]
        public string JobTitle { get; set; }
        [Column("EmirateItemID")]
        public int? EmirateItemId { get; set; }
        [Column("FieldOFWorkID")]
        public int? FieldOfworkId { get; set; }
        [Column("TitleID")]
        public int? TitleId { get; set; }
        public int? LineManagerTitleId { get; set; }
        public bool? IsYouReportToSomeone { get; set; }
        public bool? IsSomeoneReportToYou { get; set; }
        public string NextPosition { get; set; }
        public string JobDescription { get; set; }

        [ForeignKey(nameof(CountryId))]
        [InverseProperty("ProfileWorkExperiences")]
        public virtual Country Country { get; set; }
        [ForeignKey(nameof(EmirateItemId))]
        [InverseProperty(nameof(LookupItem.ProfileWorkExperiences))]
        public virtual LookupItem EmirateItem { get; set; }
        [ForeignKey(nameof(FieldOfworkId))]
        [InverseProperty(nameof(WorkField.ProfileWorkExperiences))]
        public virtual WorkField FieldOfwork { get; set; }
        [ForeignKey(nameof(IndustryId))]
        [InverseProperty("ProfileWorkExperiences")]
        public virtual Industry Industry { get; set; }
        [ForeignKey(nameof(OrganizationId))]
        [InverseProperty(nameof(GlpOrganization.ProfileWorkExperiences))]
        public virtual GlpOrganization Organization { get; set; }
        [ForeignKey(nameof(ProfileId))]
        [InverseProperty("ProfileWorkExperiences")]
        public virtual Profile Profile { get; set; }
        [ForeignKey(nameof(TitleId))]
        [InverseProperty(nameof(ProfileWorkExperienceJobTitle.ProfileWorkExperiences))]
        public virtual ProfileWorkExperienceJobTitle Title { get; set; }

        [ForeignKey(nameof(LineManagerTitleId))]
        public virtual ProfileWorkExperienceJobTitle LineManagerTitle { get; set; }

    }
}