// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("ProfileAdminComment")]
    public partial class ProfileAdminComment
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("ProfileID")]
        public int ProfileId { get; set; }
        [Column("AdminID")]
        public int AdminId { get; set; }
        [Required]
        [StringLength(1000)]
        public string Comment { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }

        [ForeignKey(nameof(AdminId))]
        [InverseProperty(nameof(User.ProfileAdminComments))]
        public virtual User Admin { get; set; }
        [ForeignKey(nameof(ProfileId))]
        [InverseProperty("ProfileAdminComments")]
        public virtual Profile Profile { get; set; }
    }
}