// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("ProfileSkill_Endorsement", Schema = "app")]
    public partial class ProfileSkillEndorsement
    {

        [Key, Column("ProfileSkillID",Order = 0)]
        public int ProfileSkillId { get; set; }
        [Key, Column("ProfileID", Order = 1)]
        public int ProfileId { get; set; }

        [Key, Column("PublicProfileID", Order = 2)]
        public int PublicProfileId { get; set; }

        [ForeignKey(nameof(ProfileId))]
        public virtual Profile Profile { get; set; }

        [ForeignKey(nameof(PublicProfileId))]
        public virtual Profile PublicProfile { get; set; }

        [ForeignKey(nameof(ProfileSkillId))]
        public virtual ProfileSkill ProfileSkill { get; set; }
    }
}