// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("Profile_LearningPreference")]
    public partial class ProfileLearningPreference
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("ProfileID")]
        public int ProfileId { get; set; }
        [Column("LearningPreferenceItemID")]
        public int LearningPreferenceItemId { get; set; }
        public int ItemOrder { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }

        [ForeignKey(nameof(LearningPreferenceItemId))]
        [InverseProperty(nameof(LookupItem.ProfileLearningPreferences))]
        public virtual LookupItem LearningPreferenceItem { get; set; }
        [ForeignKey(nameof(ProfileId))]
        [InverseProperty("ProfileLearningPreferences")]
        public virtual Profile Profile { get; set; }
    }
}