// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("ProfileEducation")]
    public partial class ProfileEducation
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("ProfileID")]
        public int ProfileId { get; set; }
        [Column("OrganizationID")]
        public int OrganizationId { get; set; }
        [Column("CountryID")]
        public int CountryId { get; set; }
        [Column("DegreeItemID")]
        public int DegreeItemId { get; set; }
        public string Year { get; set; }
        [Required]
        [StringLength(200)]
        public string Title { get; set; }
        public bool Finshed { get; set; }
        [Column("AttachmentFileID")]
        public Guid? AttachmentFileId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        public string FieldOfStudy { get; set; }
        [Column("EmirateItemID")]
        public int? EmirateItemId { get; set; }
        [Column("FieldOfStudyID")]
        public int? FieldOfStudyId { get; set; }

        [ForeignKey(nameof(CountryId))]
        [InverseProperty("ProfileEducations")]
        public virtual Country Country { get; set; }
        [ForeignKey(nameof(DegreeItemId))]
        [InverseProperty(nameof(LookupItem.ProfileEducationDegreeItems))]
        public virtual LookupItem DegreeItem { get; set; }
        [ForeignKey(nameof(EmirateItemId))]
        [InverseProperty(nameof(LookupItem.ProfileEducationEmirateItems))]
        public virtual LookupItem EmirateItem { get; set; }
        [ForeignKey(nameof(FieldOfStudyId))]
        [InverseProperty(nameof(ProfileEducationFieldOfStudy.ProfileEducations))]
        public virtual ProfileEducationFieldOfStudy FieldOfStudyNavigation { get; set; }
        [ForeignKey(nameof(OrganizationId))]
        [InverseProperty(nameof(GlpOrganization.ProfileEducations))]
        public virtual GlpOrganization Organization { get; set; }
        [ForeignKey(nameof(ProfileId))]
        [InverseProperty("ProfileEducations")]
        public virtual Profile Profile { get; set; }
    }
}