// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("ProfileTraining")]
    public partial class ProfileTraining
    {
        public ProfileTraining()
        {
            ApplicationTrainings = new HashSet<ApplicationTraining>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [StringLength(300)]
        public string Title { get; set; }
        [Column("OrganizationID")]
        public int OrganizationId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Date { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column("ProfileID")]
        public int ProfileId { get; set; }
        public int HaveCertificate { get; set; }

        [ForeignKey(nameof(OrganizationId))]
        [InverseProperty(nameof(GlpOrganization.ProfileTrainings))]
        public virtual GlpOrganization Organization { get; set; }
        [ForeignKey(nameof(ProfileId))]
        [InverseProperty("ProfileTrainings")]
        public virtual Profile Profile { get; set; }
        [InverseProperty(nameof(ApplicationTraining.Training))]
        public virtual ICollection<ApplicationTraining> ApplicationTrainings { get; set; }
    }
}