// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Uaeglp.LangModel
{
    public partial class DeviceDwell
    {
        public int Id { get; set; }
        public string DeviceId { get; set; }
        public int CenterId { get; set; }
        public DateTime CreatedDate { get; set; }
        public int IsActive { get; set; }
    }
}