// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Uaeglp.LangModel
{
    public partial class LanguageQuestions
    {
        public int Id { get; set; }
        public int? QuestionId { get; set; }
        public string Language { get; set; }
        public string LangQuestiondesc { get; set; }
        public string LangQuestiondesc2 { get; set; }
        public int? IsActive { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? IsActive1 { get; set; }
    }
}