// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Uaeglp.LangModel
{
    public partial class LanguagesLabelBak
    {
        public int Id { get; set; }
        public string Pagename { get; set; }
        public string PageDisplayname { get; set; }
        public string Labelname { get; set; }
        public string Value { get; set; }
        public string LanguageCode { get; set; }
        public int? IsActive { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
    }
}