// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Uaeglp.LangModel
{
    public partial class Languages_Label
    {
        public int Id { get; set; }
        public string Pagename { get; set; }
        public string Page_Displayname { get; set; }
        public string Labelname { get; set; }
        public string Value { get; set; }
        public string Language_Code { get; set; }
        public int? Is_Active { get; set; }
        public int? Created_By { get; set; }
        public DateTime? Created_Date { get; set; }
        public int? Updated_By { get; set; }
        public DateTime? Updated_Date { get; set; }
    }
}