// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Uaeglp.LangModel
{
    public partial class LogBugs
    {
        public int Id { get; set; }
        public string Userid { get; set; }
        public string Remoteip { get; set; }
        public string Message { get; set; }
        public string Deviceid { get; set; }
        public string Activity { get; set; }
        public byte IsActive { get; set; }
        public DateTime CreatedDate { get; set; }
        public int CreatedBy { get; set; }
    }
}