// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Uaeglp.LangModel
{
    public partial class Notifications
    {
        public int Id { get; set; }
        public int? UserId { get; set; }
        public string Title { get; set; }
        public string Message { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? CreatedBy { get; set; }
        public string Devicetoken { get; set; }
        public string Ipaddress { get; set; }
        public string Deviceid { get; set; }
        public string Devicename { get; set; }
        public byte IsActive { get; set; }
    }
}