// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Uaeglp.LangModel
{
    public partial class Settings
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public int? Value { get; set; }
        public string Label { get; set; }
        public int? UpdateBy { get; set; }
        public DateTime? UpdateDate { get; set; }
        public int? IsActive { get; set; }
    }
}