// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Uaeglp.LangModel
{
    public partial class SettingsLabel
    {
        public int Id { get; set; }
        public string Pagename { get; set; }
        public string PageDisplayname { get; set; }
        public string Labelname { get; set; }
        public int? Sequence { get; set; }
        public int? IsActive { get; set; }
    }
}