// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Uaeglp.LangModel
{
    public partial class Settings2
    {
        public int Id { get; set; }
        public string Type { get; set; }
        public byte[] Image { get; set; }
        public string ImageName { get; set; }
        public int? IsActive { get; set; }
    }
}