// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Uaeglp.LangModel
{
    public partial class SettingsComments
    {
        public int Id { get; set; }
        public string Commentsquestionlabel { get; set; }
        public string CommentsquestionlabelAr { get; set; }
        public string Commentsplaceholderlabel { get; set; }
        public string CommentsplaceholderlabelAr { get; set; }
        public string Employeelabel { get; set; }
        public string EmployeelabelAr { get; set; }
        public string Employeeplaceholderlabel { get; set; }
        public string EmployeeplaceholderlabelAr { get; set; }
        public string LanguageCode { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? UpdatedBy { get; set; }
    }
}