// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Uaeglp.LangModel
{
    public partial class SysAccessMaster
    {
        public int Id { get; set; }
        public string DisplayName { get; set; }
        public string SystemName { get; set; }
    }
}