// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Uaeglp.LangModel
{
    public partial class TempFeedback
    {
        public int Id { get; set; }
        public string DeviceId { get; set; }
        public int? CenterId { get; set; }
        public int? QuestionId { get; set; }
        public string Language { get; set; }
        public decimal? Latitude { get; set; }
        public decimal? Longitude { get; set; }
        public DateTime? CreatedDate { get; set; }
    }
}