// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Uaeglp.LangModel
{
    public partial class UserFeedbackscreens
    {
        public int Id { get; set; }
        public string Screens { get; set; }
        public int? Mandatoryscreen { get; set; }
        public int? Isvisible { get; set; }
        public int? IsEdit { get; set; }
        public int? Totalscreencount { get; set; }
        public int? Currentscreenindex { get; set; }
        public string Comments { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? UpdatedBy { get; set; }
    }
}