// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Uaeglp.LangModel
{
    public partial class UserComments
    {
        public int Id { get; set; }
        public string Comments1 { get; set; }
        public string Comments2 { get; set; }
        public string Employee { get; set; }
        public int? Questionid { get; set; }
        public int? CenterId { get; set; }
        public int? FeedbackId { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? IsActive { get; set; }
    }
}