// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Uaeglp.LangModel
{
    public partial class UserAnswer
    {
        public int Id { get; set; }
        public int FeedbackId { get; set; }
        public int QuestionId { get; set; }
        public int AnswerId { get; set; }
        public string AnswerOther { get; set; }
        public int? CenterId { get; set; }
        public int CreatedBy { get; set; }
        public DateTime CreatedDate { get; set; }
        public int? UpdatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int IsActive { get; set; }
    }
}