// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Uaeglp.LangModel
{
    public partial class VwSurveyanswers
    {
        public int Id { get; set; }
        public string AnswerEn { get; set; }
        public string CenterName { get; set; }
        public int? EntityId { get; set; }
        public string EntityName { get; set; }
        public int? CityId { get; set; }
        public string CityName { get; set; }
        public int? FeedbacId { get; set; }
        public int? CenterId { get; set; }
        public int? QuestionId { get; set; }
        public string Language { get; set; }
        public DateTime? CreatedDate { get; set; }
    }
}