// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;

namespace Uaeglp.LangModel
{
    public partial class WebUsers
    {
        public int Id { get; set; }
        public string EmployeeId { get; set; }
        public string Username { get; set; }
        public string Name { get; set; }
        public string Password { get; set; }
        public byte? IsSuperadmin { get; set; }
        public string EmailId { get; set; }
        public int? RoleId { get; set; }
        public string Mobileno { get; set; }
        public DateTime? Logintime { get; set; }
        public DateTime? Logouttime { get; set; }
        public string Remoteip { get; set; }
        public byte? IsActive { get; set; }
        public DateTime? CreatedDate { get; set; }
        public int? CreatedBy { get; set; }
        public DateTime? UpdatedDate { get; set; }
        public int? UpdatedBy { get; set; }
    }
}