// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("AssessmentBlock")]
    public partial class AssessmentBlock
    {
        public AssessmentBlock()
        {
            QuestionHeads = new HashSet<QuestionHead>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [Column("NameEN")]
        [StringLength(100)]
        public string NameEn { get; set; }
        [Required]
        [Column("NameAR")]
        [StringLength(100)]
        public string NameAr { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column("LevelID")]
        public int? LevelId { get; set; }
        [Column("SubAssessmenttoolID")]
        public int SubAssessmenttoolId { get; set; }
        [Column("AssessmenttoolID")]
        public int AssessmenttoolId { get; set; }

        [ForeignKey(nameof(AssessmenttoolId))]
        [InverseProperty(nameof(AssessmentTool.AssessmentBlocks))]
        public virtual AssessmentTool Assessmenttool { get; set; }
        [ForeignKey(nameof(LevelId))]
        [InverseProperty(nameof(LookupItem.AssessmentBlocks))]
        public virtual LookupItem Level { get; set; }
        [ForeignKey(nameof(SubAssessmenttoolId))]
        [InverseProperty(nameof(SubAssessmentTool.AssessmentBlocks))]
        public virtual SubAssessmentTool SubAssessmenttool { get; set; }
        [InverseProperty(nameof(QuestionHead.Assessmentblock))]
        public virtual ICollection<QuestionHead> QuestionHeads { get; set; }
    }
}