// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    public partial class AssessmentNumber
    {
        [Column("ID")]
        public int Id { get; set; }
        public int Number { get; set; }
    }
}