// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("AssessmentGroupMember")]
    public partial class AssessmentGroupMember
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Column("ProfileID")]
        public int ProfileId { get; set; }
        [Column("AssessmentGroupID")]
        public int AssessmentGroupId { get; set; }
        public bool IsCoordinator { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? AssessmentCompletionDatetime { get; set; }
        public bool IsAssessmentCompleted { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal AssessmentCompletionPercentage { get; set; }
        public int Rank { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal ProfileWeightedPercentage { get; set; }
        public int CompletedCount { get; set; }
        public int TotalCount { get; set; }

        [ForeignKey(nameof(AssessmentGroupId))]
        [InverseProperty("AssessmentGroupMembers")]
        public virtual AssessmentGroup AssessmentGroup { get; set; }
        [ForeignKey(nameof(ProfileId))]
        [InverseProperty("AssessmentGroupMembers")]
        public virtual Profile Profile { get; set; }
    }
}