// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("AssessmentNarrativeReport")]
    public partial class AssessmentNarrativeReport
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column("AssessmentCategoryID")]
        public int AssessmentCategoryId { get; set; }
        [Column("NameEN")]
        public string NameEn { get; set; }
        [Column("NameAR")]
        public string NameAr { get; set; }
        [Column("TextEN")]
        public string TextEn { get; set; }
        [Column("TextAR")]
        public string TextAr { get; set; }

        [ForeignKey(nameof(AssessmentCategoryId))]
        [InverseProperty(nameof(LookupItem.AssessmentNarrativeReports))]
        public virtual LookupItem AssessmentCategory { get; set; }
    }
}