// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("Assignment")]
    public partial class Assignment
    {
        public Assignment()
        {
            AssignmentAnswers = new HashSet<AssignmentAnswer>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("BatchID")]
        public int BatchId { get; set; }
        [Required]
        [StringLength(300)]
        public string Title { get; set; }
        [Required]
        public string Description { get; set; }
        [Column("CorrelationID")]
        public Guid? CorrelationId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DueDate { get; set; }
        public bool IsOptional { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }

        [ForeignKey(nameof(BatchId))]
        [InverseProperty("Assignments")]
        public virtual Batch Batch { get; set; }
        [InverseProperty(nameof(AssignmentAnswer.Assighment))]
        public virtual ICollection<AssignmentAnswer> AssignmentAnswers { get; set; }
    }
}