// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("AssignedAssessment")]
    public partial class AssignedAssessment
    {
        public AssignedAssessment()
        {
            ProfileAssignedAssessments = new HashSet<ProfileAssignedAssessment>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateFrom { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime DateTo { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? AssessmentCompletionDatetime { get; set; }
        public bool IsAssessmentCompleted { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal AssessmentCompletionPercentage { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal ProfileWeightedPercentage { get; set; }
        [Column("AssessmentToolMatrixID")]
        public int AssessmentToolMatrixId { get; set; }
        [Column("ProfileID")]
        public int ProfileId { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Column("NameEN")]
        public string NameEn { get; set; }
        [Column("NameAR")]
        public string NameAr { get; set; }

        [ForeignKey(nameof(AssessmentToolMatrixId))]
        [InverseProperty("AssignedAssessments")]
        public virtual AssessmentToolMatrix AssessmentToolMatrix { get; set; }
        [ForeignKey(nameof(ProfileId))]
        [InverseProperty("AssignedAssessments")]
        public virtual Profile Profile { get; set; }
        [InverseProperty(nameof(ProfileAssignedAssessment.AssignedAssessment))]
        public virtual ICollection<ProfileAssignedAssessment> ProfileAssignedAssessments { get; set; }
    }
}