// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("Batch_AssessmentTools")]
    public partial class BatchAssessmentTool
    {
        [Key]
        [Column("Batch_ID")]
        public int BatchId { get; set; }
        [Key]
        [Column("AssessmentTool_ID")]
        public int AssessmentToolId { get; set; }

        [ForeignKey(nameof(AssessmentToolId))]
        [InverseProperty("BatchAssessmentTools")]
        public virtual AssessmentTool AssessmentTool { get; set; }
        [ForeignKey(nameof(BatchId))]
        [InverseProperty("BatchAssessmentTools")]
        public virtual Batch Batch { get; set; }
    }
}