// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("ProfileBatchAssessment")]
    public partial class ProfileBatchAssessment
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column("ProfileID")]
        public int ProfileId { get; set; }
        [Column("BatchID")]
        public int BatchId { get; set; }
        [Column("ApplicationID")]
        public int ApplicationId { get; set; }
        [Column("ProfileAssessmenttoolID")]
        public int ProfileAssessmenttoolId { get; set; }

        [ForeignKey(nameof(ApplicationId))]
        [InverseProperty("ProfileBatchAssessments")]
        public virtual Application Application { get; set; }
        [ForeignKey(nameof(BatchId))]
        [InverseProperty("ProfileBatchAssessments")]
        public virtual Batch Batch { get; set; }
        [ForeignKey(nameof(ProfileId))]
        [InverseProperty("ProfileBatchAssessments")]
        public virtual Profile Profile { get; set; }
        [ForeignKey(nameof(ProfileAssessmenttoolId))]
        [InverseProperty(nameof(ProfileAssessmentToolScore.ProfileBatchAssessments))]
        public virtual ProfileAssessmentToolScore ProfileAssessmenttool { get; set; }
    }
}