// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("ProfileSubScaleScore")]
    public partial class ProfileSubScaleScore
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("ProfileID")]
        public int ProfileId { get; set; }
        [Column("SubScaleID")]
        public int SubScaleId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Score { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        public int Order { get; set; }
        [Column(TypeName = "decimal(20, 10)")]
        public decimal? StandardScore { get; set; }
        [Column("TScore", TypeName = "decimal(20, 10)")]
        public decimal? Tscore { get; set; }
        [Column("STENScore", TypeName = "decimal(20, 10)")]
        public decimal? Stenscore { get; set; }
        [Column(TypeName = "decimal(20, 10)")]
        public decimal? PercentileScore { get; set; }
        [Required]
        public bool? IsCompleted { get; set; }
        [Column(TypeName = "decimal(20, 10)")]
        public decimal? CompetencyScore { get; set; }
        [Column("CompetencyID")]
        public int? CompetencyId { get; set; }
        [Column(TypeName = "decimal(20, 10)")]
        public decimal? Mean { get; set; }
        [Column(TypeName = "decimal(20, 10)")]
        public decimal? StandardDeviation { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? RecalculatedDatetime { get; set; }

        [ForeignKey(nameof(CompetencyId))]
        [InverseProperty("ProfileSubScaleScores")]
        public virtual Competency Competency { get; set; }
        [ForeignKey(nameof(ProfileId))]
        [InverseProperty("ProfileSubScaleScores")]
        public virtual Profile Profile { get; set; }
        [ForeignKey(nameof(SubScaleId))]
        [InverseProperty("ProfileSubScaleScores")]
        public virtual SubScale SubScale { get; set; }
    }
}