// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("ProfileAssessmentToolScore")]
    public partial class ProfileAssessmentToolScore
    {
        public ProfileAssessmentToolScore()
        {
            AssessmentReportFeedbacks = new HashSet<AssessmentReportFeedback>();
            ProfileAssignedAssessments = new HashSet<ProfileAssignedAssessment>();
            ProfileBatchAssessments = new HashSet<ProfileBatchAssessment>();
            ProfileGroupAssessments = new HashSet<ProfileGroupAssessment>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("ProfileID")]
        public int ProfileId { get; set; }
        [Column("AssessmentToolID")]
        public int AssessmentToolId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Score { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        public int Order { get; set; }
        [Required]
        public bool? IsCompleted { get; set; }
        [Column(TypeName = "decimal(20, 10)")]
        public decimal? CompetencyTotalScore { get; set; }
        public bool? IsFailed { get; set; }
        [Column(TypeName = "decimal(20, 10)")]
        public decimal? StandardScore { get; set; }
        [Column("TScore", TypeName = "decimal(20, 10)")]
        public decimal? Tscore { get; set; }
        [Column("STENScore", TypeName = "decimal(20, 10)")]
        public decimal? Stenscore { get; set; }
        public bool IsUpdated { get; set; }
        [Column(TypeName = "decimal(20, 10)")]
        public decimal? RawScore { get; set; }
        [Column(TypeName = "decimal(20, 10)")]
        public decimal? Mean { get; set; }
        [Column(TypeName = "decimal(20, 10)")]
        public decimal? StandardDeviation { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? RecalculatedDatetime { get; set; }
        public bool IsProcessing { get; set; }

        [ForeignKey(nameof(AssessmentToolId))]
        [InverseProperty("ProfileAssessmentToolScores")]
        public virtual AssessmentTool AssessmentTool { get; set; }
        [ForeignKey(nameof(ProfileId))]
        [InverseProperty("ProfileAssessmentToolScores")]
        public virtual Profile Profile { get; set; }
        [InverseProperty(nameof(AssessmentReportFeedback.ProfileAssesmentToolScore))]
        public virtual ICollection<AssessmentReportFeedback> AssessmentReportFeedbacks { get; set; }
        [InverseProperty(nameof(ProfileAssignedAssessment.ProfileAssessmenttool))]
        public virtual ICollection<ProfileAssignedAssessment> ProfileAssignedAssessments { get; set; }
        [InverseProperty(nameof(ProfileBatchAssessment.ProfileAssessmenttool))]
        public virtual ICollection<ProfileBatchAssessment> ProfileBatchAssessments { get; set; }
        [InverseProperty(nameof(ProfileGroupAssessment.ProfileAssessmenttool))]
        public virtual ICollection<ProfileGroupAssessment> ProfileGroupAssessments { get; set; }
    }
}