// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("ADConnection", Schema = "bbsf")]
    public partial class Adconnection
    {
        public Adconnection()
        {
            Admappings = new HashSet<Admapping>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        public string Name { get; set; }
        [Column("PermissionSetID")]
        public int PermissionSetId { get; set; }
        [Column("ADConnectionTypeItemID")]
        public int AdconnectionTypeItemId { get; set; }
        [Required]
        [StringLength(256)]
        public string Identifier { get; set; }
        [Required]
        [StringLength(256)]
        public string Domain { get; set; }
        [StringLength(20)]
        public string SamAccount { get; set; }
        [StringLength(32)]
        public string Password { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        public bool MarkAsInactive { get; set; }
        public bool AddToDailyJob { get; set; }
        public string LastRunLog { get; set; }
        [Column("WelcomeTemplateID")]
        public int? WelcomeTemplateId { get; set; }
        [Required]
        [StringLength(2)]
        public string LangKey { get; set; }
        public bool IsRunningNow { get; set; }

        [ForeignKey(nameof(AdconnectionTypeItemId))]
        [InverseProperty(nameof(LookupItem.Adconnections))]
        public virtual LookupItem AdconnectionTypeItem { get; set; }
        [ForeignKey(nameof(PermissionSetId))]
        [InverseProperty("Adconnections")]
        public virtual PermissionSet PermissionSet { get; set; }
        [ForeignKey(nameof(WelcomeTemplateId))]
        [InverseProperty(nameof(Template.Adconnections))]
        public virtual Template WelcomeTemplate { get; set; }
        [InverseProperty(nameof(Admapping.Adconnection))]
        public virtual ICollection<Admapping> Admappings { get; set; }
    }
}