// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("ADMapping", Schema = "bbsf")]
    public partial class Admapping
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("ADConnectionID")]
        public int AdconnectionId { get; set; }
        [Required]
        [Column("BBSFPropertyName")]
        [StringLength(1024)]
        public string BbsfpropertyName { get; set; }
        [Required]
        [Column("ADPropertyName")]
        [StringLength(1024)]
        public string AdpropertyName { get; set; }
        [Column("ADMappingTypeItemID")]
        public int AdmappingTypeItemId { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }

        [ForeignKey(nameof(AdconnectionId))]
        [InverseProperty("Admappings")]
        public virtual Adconnection Adconnection { get; set; }
        [ForeignKey(nameof(AdmappingTypeItemId))]
        [InverseProperty(nameof(LookupItem.Admappings))]
        public virtual LookupItem AdmappingTypeItem { get; set; }
    }
}