// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    public partial class Agendum
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [StringLength(50)]
        public string Subject { get; set; }
        [Column("MeetupID")]
        public int MeetupId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Day { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Time { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }

        [ForeignKey(nameof(MeetupId))]
        [InverseProperty("Agenda")]
        public virtual Meetup Meetup { get; set; }
    }
}