// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("ApplicationProgress")]
    public partial class ApplicationProgress
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("ApplicationID")]
        public int ApplicationId { get; set; }
        [Column("ApplicationSectionItemID")]
        public int ApplicationSectionItemId { get; set; }
        [Column("ApplicationSectionStatusItemID")]
        public int ApplicationSectionStatusItemId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? Progress { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }

        [ForeignKey(nameof(ApplicationId))]
        [InverseProperty("ApplicationProgresses")]
        public virtual Application Application { get; set; }
        [ForeignKey(nameof(ApplicationSectionItemId))]
        [InverseProperty(nameof(LookupItem.ApplicationProgressApplicationSectionItems))]
        public virtual LookupItem ApplicationSectionItem { get; set; }
        [ForeignKey(nameof(ApplicationSectionStatusItemId))]
        [InverseProperty(nameof(LookupItem.ApplicationProgressApplicationSectionStatusItems))]
        public virtual LookupItem ApplicationSectionStatusItem { get; set; }
    }
}