// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("ApplicationTraining")]
    public partial class ApplicationTraining
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("TrainingID")]
        public int? TrainingId { get; set; }
        [Required]
        [StringLength(300)]
        public string Title { get; set; }
        [Column("OrganizationID")]
        public int OrganizationId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Date { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column("ProfileID")]
        public int ProfileId { get; set; }
        [Column("ApplicationID")]
        public int ApplicationId { get; set; }
        public int HaveCertificate { get; set; }

        [ForeignKey(nameof(ApplicationId))]
        [InverseProperty("ApplicationTrainings")]
        public virtual Application Application { get; set; }
        [ForeignKey(nameof(OrganizationId))]
        [InverseProperty(nameof(GlpOrganization.ApplicationTrainings))]
        public virtual GlpOrganization Organization { get; set; }
        [ForeignKey(nameof(ProfileId))]
        [InverseProperty("ApplicationTrainings")]
        public virtual Profile Profile { get; set; }
        [ForeignKey(nameof(TrainingId))]
        [InverseProperty(nameof(ProfileTraining.ApplicationTrainings))]
        public virtual ProfileTraining Training { get; set; }
    }
}