// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("ApplicationAchievement")]
    public partial class ApplicationAchievement
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Date { get; set; }
        [StringLength(4000)]
        public string Description { get; set; }
        [Column("OrgnizationID")]
        public int? OrgnizationId { get; set; }
        [StringLength(300)]
        public string Role { get; set; }
        [Column("ApplicationID")]
        public int ApplicationId { get; set; }
        [Column("AchievementID")]
        public int? AchievementId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column("ProfileID")]
        public int ProfileId { get; set; }
        [StringLength(300)]
        public string ProjectTitleAndEvent { get; set; }
        [Column("VerbID")]
        public int VerbId { get; set; }
        [Column("AwardItemID")]
        public int? AwardItemId { get; set; }
        [Column("MedalItemID")]
        public int? MedalItemId { get; set; }
        [Column("ReachedItemID")]
        public int? ReachedItemId { get; set; }

        [ForeignKey(nameof(AchievementId))]
        [InverseProperty(nameof(ProfileAchievement.ApplicationAchievements))]
        public virtual ProfileAchievement Achievement { get; set; }
        [ForeignKey(nameof(ApplicationId))]
        [InverseProperty("ApplicationAchievements")]
        public virtual Application Application { get; set; }
        [ForeignKey(nameof(AwardItemId))]
        [InverseProperty(nameof(LookupItem.ApplicationAchievementAwardItems))]
        public virtual LookupItem AwardItem { get; set; }
        [ForeignKey(nameof(MedalItemId))]
        [InverseProperty(nameof(LookupItem.ApplicationAchievementMedalItems))]
        public virtual LookupItem MedalItem { get; set; }
        [ForeignKey(nameof(OrgnizationId))]
        [InverseProperty(nameof(GlpOrganization.ApplicationAchievements))]
        public virtual GlpOrganization Orgnization { get; set; }
        [ForeignKey(nameof(ProfileId))]
        [InverseProperty("ApplicationAchievements")]
        public virtual Profile Profile { get; set; }
        [ForeignKey(nameof(ReachedItemId))]
        [InverseProperty(nameof(LookupItem.ApplicationAchievementReachedItems))]
        public virtual LookupItem ReachedItem { get; set; }
    }
}