// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("BadgeRequest")]
    public partial class BadgeRequest
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("ProfileID")]
        public int ProfileId { get; set; }
        [Column("BadgeID")]
        public int BadgeId { get; set; }
        [Column("StatusID")]
        public int StatusId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? RequestDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ApprovalDate { get; set; }
        public string Comment { get; set; }
        [Column("FileID")]
        public Guid? FileId { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        public int? Points { get; set; }

        [ForeignKey(nameof(BadgeId))]
        [InverseProperty("BadgeRequests")]
        public virtual Badge Badge { get; set; }
        [ForeignKey(nameof(ProfileId))]
        [InverseProperty(nameof(User.BadgeRequests))]
        public virtual User Profile { get; set; }
        [ForeignKey(nameof(StatusId))]
        [InverseProperty(nameof(LookupItem.BadgeRequests))]
        public virtual LookupItem Status { get; set; }
    }
}