// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("BatchInitiative")]
    public partial class BatchInitiative
    {
        [Key]
        [Column("Batch_ID")]
        public int BatchId { get; set; }
        [Key]
        [Column("Initiative_ID")]
        public int InitiativeId { get; set; }

        [ForeignKey(nameof(BatchId))]
        [InverseProperty("BatchInitiatives")]
        public virtual Batch Batch { get; set; }
        [ForeignKey(nameof(InitiativeId))]
        [InverseProperty("BatchInitiatives")]
        public virtual Initiative Initiative { get; set; }
    }
}