// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("Challenge")]
    public partial class Challenge
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [Column("TitleEN")]
        [StringLength(255)]
        public string TitleEn { get; set; }
        [Required]
        [Column("TitleAR")]
        [StringLength(255)]
        public string TitleAr { get; set; }
        [Required]
        [Column("DescriptionEN")]
        [StringLength(255)]
        public string DescriptionEn { get; set; }
        [Required]
        [Column("DescriptionAR")]
        [StringLength(255)]
        public string DescriptionAr { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime StartDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime EndDate { get; set; }
        [Column("GovernmentEntityID")]
        public int GovernmentEntityId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }

        [ForeignKey(nameof(GovernmentEntityId))]
        [InverseProperty("Challenges")]
        public virtual GovernmentEntity GovernmentEntity { get; set; }
    }
}