// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("ChatRoom_User", Schema = "bbsf")]
    public partial class ChatRoomUser
    {
        [Key]
        [Column("ChatRoomID")]
        public int ChatRoomId { get; set; }
        [Key]
        [Column("UserID")]
        public int UserId { get; set; }

        [ForeignKey(nameof(ChatRoomId))]
        [InverseProperty("ChatRoomUsers")]
        public virtual ChatRoom ChatRoom { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty("ChatRoomUsers")]
        public virtual User User { get; set; }
    }
}