// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("ChatRoom", Schema = "bbsf")]
    public partial class ChatRoom
    {
        public ChatRoom()
        {
            ChatMessages = new HashSet<ChatMessage>();
            ChatRoomUsers = new HashSet<ChatRoomUser>();
            ChatUnreadMessages = new HashSet<ChatUnreadMessage>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("OwnerID")]
        public int OwnerId { get; set; }
        [Column("RoomTypeItemID")]
        public int RoomTypeItemId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column("TitleEN")]
        public string TitleEn { get; set; }
        [Column("TitleAR")]
        public string TitleAr { get; set; }

        [ForeignKey(nameof(RoomTypeItemId))]
        [InverseProperty(nameof(LookupItem.ChatRooms))]
        public virtual LookupItem RoomTypeItem { get; set; }
        [InverseProperty(nameof(ChatMessage.Room))]
        public virtual ICollection<ChatMessage> ChatMessages { get; set; }
        [InverseProperty(nameof(ChatRoomUser.ChatRoom))]
        public virtual ICollection<ChatRoomUser> ChatRoomUsers { get; set; }
        [InverseProperty(nameof(ChatUnreadMessage.Room))]
        public virtual ICollection<ChatUnreadMessage> ChatUnreadMessages { get; set; }
    }
}