// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("ChatMessage", Schema = "bbsf")]
    public partial class ChatMessage
    {
        public ChatMessage()
        {
            ChatMessageAttachments = new HashSet<ChatMessageAttachment>();
            ChatMessageSeenBies = new HashSet<ChatMessageSeenBy>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [StringLength(1000)]
        public string MessageText { get; set; }
        [Column("RoomID")]
        public int RoomId { get; set; }
        [Column("MessageTypeItemID")]
        public int MessageTypeItemId { get; set; }
        [Column("OwnerID")]
        public int OwnerId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column("ImageID")]
        public int? ImageId { get; set; }
        [Column("FileID")]
        public int? FileId { get; set; }

        [ForeignKey(nameof(MessageTypeItemId))]
        [InverseProperty(nameof(LookupItem.ChatMessages))]
        public virtual LookupItem MessageTypeItem { get; set; }
        [ForeignKey(nameof(OwnerId))]
        [InverseProperty(nameof(User.ChatMessages))]
        public virtual User Owner { get; set; }
        [ForeignKey(nameof(RoomId))]
        [InverseProperty(nameof(ChatRoom.ChatMessages))]
        public virtual ChatRoom Room { get; set; }
        [InverseProperty(nameof(ChatMessageAttachment.ChatMessage))]
        public virtual ICollection<ChatMessageAttachment> ChatMessageAttachments { get; set; }
        [InverseProperty(nameof(ChatMessageSeenBy.Message))]
        public virtual ICollection<ChatMessageSeenBy> ChatMessageSeenBies { get; set; }
    }
}