// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("ChatUnreadMessage", Schema = "bbsf")]
    public partial class ChatUnreadMessage
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("RoomID")]
        public int RoomId { get; set; }
        [Column("UserID")]
        public int UserId { get; set; }
        public int MessagesCount { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        public bool Archived { get; set; }

        [ForeignKey(nameof(RoomId))]
        [InverseProperty(nameof(ChatRoom.ChatUnreadMessages))]
        public virtual ChatRoom Room { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty("ChatUnreadMessages")]
        public virtual User User { get; set; }
    }
}