// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("CompetencySubscale")]
    public partial class CompetencySubscale
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column("CompetencyID")]
        public int? CompetencyId { get; set; }
        [Column("SubscaleID")]
        public int? SubscaleId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal Weight { get; set; }

        [ForeignKey(nameof(CompetencyId))]
        [InverseProperty("CompetencySubscales")]
        public virtual Competency Competency { get; set; }
        [ForeignKey(nameof(SubscaleId))]
        [InverseProperty(nameof(SubScale.CompetencySubscales))]
        public virtual SubScale Subscale { get; set; }
    }
}