// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("CompetencyAssessmentTool")]
    public partial class CompetencyAssessmentTool
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column(TypeName = "decimal(20, 10)")]
        public decimal? Mean { get; set; }
        [Column(TypeName = "decimal(20, 10)")]
        public decimal? StandardDeviation { get; set; }
        [Column("CompetencyID")]
        public int CompetencyId { get; set; }
        [Column("AssessmentToolID")]
        public int AssessmentToolId { get; set; }
        [Column("NarrativeLowDescriptionEN")]
        public string NarrativeLowDescriptionEn { get; set; }
        [Column("NarrativeLowDescriptionAR")]
        public string NarrativeLowDescriptionAr { get; set; }
        [Column("NarrativeAverageDescriptionAR")]
        public string NarrativeAverageDescriptionAr { get; set; }
        [Column("NarrativeAverageDescriptionEN")]
        public string NarrativeAverageDescriptionEn { get; set; }
        [Column("NarrativeHighDescriptionEN")]
        public string NarrativeHighDescriptionEn { get; set; }
        [Column("NarrativeHighDescriptionAR")]
        public string NarrativeHighDescriptionAr { get; set; }

        [ForeignKey(nameof(AssessmentToolId))]
        [InverseProperty("CompetencyAssessmentTools")]
        public virtual AssessmentTool AssessmentTool { get; set; }
        [ForeignKey(nameof(CompetencyId))]
        [InverseProperty("CompetencyAssessmentTools")]
        public virtual Competency Competency { get; set; }
    }
}