// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("Configurations", Schema = "bbsf")]
    public partial class Configuration
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string Key { get; set; }
        [Required]
        public string Value { get; set; }
        [Column("ScopeItemID")]
        public int ScopeItemId { get; set; }
        [Column("UserID")]
        public int? UserId { get; set; }
        [Column("PermissionSetID")]
        public int? PermissionSetId { get; set; }

        [ForeignKey(nameof(PermissionSetId))]
        [InverseProperty("Configurations")]
        public virtual PermissionSet PermissionSet { get; set; }
        [ForeignKey(nameof(ScopeItemId))]
        [InverseProperty(nameof(LookupItem.Configurations))]
        public virtual LookupItem ScopeItem { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty("Configurations")]
        public virtual User User { get; set; }
    }
}