// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    public partial class Consent
    {
        [Key]
        [StringLength(200)]
        public string Subject { get; set; }
        [Key]
        [StringLength(200)]
        public string ClientId { get; set; }
        [Required]
        [StringLength(2000)]
        public string Scopes { get; set; }
    }
}