// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("Country", Schema = "bbsf")]
    public partial class Country
    {
        public Country()
        {
            ProfileEducations = new HashSet<ProfileEducation>();
            ProfileWorkExperiences = new HashSet<ProfileWorkExperience>();
            Profiles = new HashSet<Profile>();
            PublicHolidays = new HashSet<PublicHoliday>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [Column("NameEN")]
        [StringLength(50)]
        public string NameEn { get; set; }
        [Required]
        [Column("NameAR")]
        [StringLength(50)]
        public string NameAr { get; set; }
        [Required]
        [StringLength(2)]
        public string Code { get; set; }
        [Required]
        [StringLength(4)]
        public string TelCode { get; set; }

        [InverseProperty(nameof(ProfileEducation.Country))]
        public virtual ICollection<ProfileEducation> ProfileEducations { get; set; }
        [InverseProperty(nameof(ProfileWorkExperience.Country))]
        public virtual ICollection<ProfileWorkExperience> ProfileWorkExperiences { get; set; }
        [InverseProperty(nameof(Profile.ResidenceCountry))]
        public virtual ICollection<Profile> Profiles { get; set; }
        [InverseProperty(nameof(PublicHoliday.Country))]
        public virtual ICollection<PublicHoliday> PublicHolidays { get; set; }
    }
}