// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("CriteriaClaim")]
    public partial class CriteriaClaim
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("ProfileID")]
        public int ProfileId { get; set; }
        [Column("CriteriaID")]
        public int CriteriaId { get; set; }
        [Column("StatusID")]
        public int StatusId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? RequestDate { get; set; }
        public string Admin { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? AdminResponseDate { get; set; }
        public string AdminComment { get; set; }
        public string Details { get; set; }
        [Column("CorrelationID")]
        public Guid? CorrelationId { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        public bool IsDeleted { get; set; }
        public int Order { get; set; }

        [ForeignKey(nameof(CriteriaId))]
        [InverseProperty(nameof(Models.Criteria.CriteriaClaims))]
        public virtual Criteria Criteria { get; set; }
        [ForeignKey(nameof(ProfileId))]
        [InverseProperty("CriteriaClaims")]
        public virtual Profile Profile { get; set; }
        [ForeignKey(nameof(StatusId))]
        [InverseProperty(nameof(LookupItem.CriteriaClaims))]
        public virtual LookupItem Status { get; set; }
    }
}