// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    public partial class Criteria
    {
        public Criteria()
        {
            CriteriaClaims = new HashSet<CriteriaClaim>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Required]
        [Column("TitleEN")]
        public string TitleEn { get; set; }
        [Required]
        [Column("TitleAR")]
        public string TitleAr { get; set; }
        public int Points { get; set; }
        public string Description { get; set; }
        public bool RequiresApproval { get; set; }
        public bool IsVisible { get; set; }
        public bool PointEdited { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime PointEditDate { get; set; }
        public int PointEditDifference { get; set; }
        [Column("CriteriaCategoryID")]
        public int CriteriaCategoryId { get; set; }
        public bool IsDeleted { get; set; }

        [ForeignKey(nameof(CriteriaCategoryId))]
        [InverseProperty(nameof(LookupItem.Criteria))]
        public virtual LookupItem CriteriaCategory { get; set; }
        [InverseProperty(nameof(CriteriaClaim.Criteria))]
        public virtual ICollection<CriteriaClaim> CriteriaClaims { get; set; }
    }
}