// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("EResourceLink")]
    public partial class EresourceLink
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column("URL")]
        public string Url { get; set; }
        [Column("EResourceID")]
        public int EresourceId { get; set; }

        [ForeignKey(nameof(EresourceId))]
        [InverseProperty("EresourceLinks")]
        public virtual Eresource Eresource { get; set; }
    }
}