// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("Event")]
    public partial class Event
    {
        public Event()
        {
            EventDays = new HashSet<EventDay>();
            ProfileEvents = new HashSet<ProfileEvent>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("BatchID")]
        public int? BatchId { get; set; }
        [Required]
        [Column("TextEN")]
        [StringLength(100)]
        public string TextEn { get; set; }
        [Required]
        [Column("TextAR")]
        [StringLength(100)]
        public string TextAr { get; set; }
        [Column("DescriptionEN")]
        [StringLength(300)]
        public string DescriptionEn { get; set; }
        [Column("DescriptionAR")]
        [StringLength(300)]
        public string DescriptionAr { get; set; }
        [Column("LocationEN")]
        [StringLength(100)]
        public string LocationEn { get; set; }
        [Column("LocationAR")]
        [StringLength(100)]
        public string LocationAr { get; set; }
        [StringLength(50)]
        public string Longitude { get; set; }
        [StringLength(50)]
        public string Latitude { get; set; }
        [StringLength(500)]
        public string MapText { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        public string QRCode { get; set; }
        public int? RegistrationTypeItemID { get; set; }

        [ForeignKey(nameof(BatchId))]
        [InverseProperty("Events")]
        public virtual Batch Batch { get; set; }
        [InverseProperty(nameof(EventDay.Event))]
        public virtual ICollection<EventDay> EventDays { get; set; }
        [InverseProperty(nameof(ProfileEvent.Event))]
        public virtual ICollection<ProfileEvent> ProfileEvents { get; set; }
    }
}