// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("Factor")]
    public partial class Factor
    {
        public Factor()
        {
            ProfileFactorScores = new HashSet<ProfileFactorScore>();
            Scales = new HashSet<Scale>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [Column("NameEN")]
        [StringLength(100)]
        public string NameEn { get; set; }
        [Required]
        [Column("NameAR")]
        [StringLength(100)]
        public string NameAr { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column("AssessmentToolID")]
        public int AssessmentToolId { get; set; }
        [Column(TypeName = "decimal(20, 10)")]
        public decimal? Mean { get; set; }
        [Column(TypeName = "decimal(20, 10)")]
        public decimal? StandardDeviation { get; set; }

        [ForeignKey(nameof(AssessmentToolId))]
        [InverseProperty("Factors")]
        public virtual AssessmentTool AssessmentTool { get; set; }
        [InverseProperty(nameof(ProfileFactorScore.Factor))]
        public virtual ICollection<ProfileFactorScore> ProfileFactorScores { get; set; }
        [InverseProperty(nameof(Scale.Factor))]
        public virtual ICollection<Scale> Scales { get; set; }
    }
}