// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("FAQ")]
    public partial class Faq
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("QuestionEN")]
        public string QuestionEn { get; set; }
        [Column("QuestionAR")]
        public string QuestionAr { get; set; }
        [Column("AnswerEN")]
        public string AnswerEn { get; set; }
        [Column("AnswerAR")]
        public string AnswerAr { get; set; }
        [Column("ProgrammeID")]
        public int? ProgrammeId { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }

        [ForeignKey(nameof(ProgrammeId))]
        [InverseProperty("Faqs")]
        public virtual Programme Programme { get; set; }
    }
}