// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("Folder")]
    public partial class Folder
    {
        public Folder()
        {
            Eresources = new HashSet<Eresource>();
            FolderBatches = new HashSet<FolderBatch>();
            InverseParentFolder = new HashSet<Folder>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [Column("NameEN")]
        [StringLength(256)]
        public string NameEn { get; set; }
        [Required]
        [Column("NameAR")]
        [StringLength(256)]
        public string NameAr { get; set; }
        [Column("ParentFolderID")]
        public int? ParentFolderId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }

        [ForeignKey(nameof(ParentFolderId))]
        [InverseProperty(nameof(Folder.InverseParentFolder))]
        public virtual Folder ParentFolder { get; set; }
        [InverseProperty(nameof(Eresource.Folder))]
        public virtual ICollection<Eresource> Eresources { get; set; }
        [InverseProperty(nameof(FolderBatch.Folder))]
        public virtual ICollection<FolderBatch> FolderBatches { get; set; }
        [InverseProperty(nameof(Folder.ParentFolder))]
        public virtual ICollection<Folder> InverseParentFolder { get; set; }
    }
}