// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("FormsHubConnection", Schema = "bbsf")]
    public partial class FormsHubConnection
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        public int UserId { get; set; }
        [StringLength(256)]
        public string ConnectionId { get; set; }
        [StringLength(256)]
        public string ObjectId { get; set; }
        [StringLength(256)]
        public string ObjectName { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty("FormsHubConnections")]
        public virtual User User { get; set; }
    }
}