// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("GLPModel")]
    public partial class Glpmodel
    {
        public Glpmodel()
        {
            Pillars = new HashSet<Pillar>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [Column("NameEN")]
        [StringLength(100)]
        public string NameEn { get; set; }
        [Required]
        [Column("NameAR")]
        [StringLength(100)]
        public string NameAr { get; set; }
        [Column("DescriptionEN")]
        [StringLength(300)]
        public string DescriptionEn { get; set; }
        [Column("DescriptionAR")]
        [StringLength(300)]
        public string DescriptionAr { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        public bool IsPublished { get; set; }

        [InverseProperty(nameof(Pillar.Model))]
        public virtual ICollection<Pillar> Pillars { get; set; }
    }
}