// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("GlpOrganization_ItemTypes")]
    public partial class GlpOrganizationItemType
    {
        [Key]
        [Column("GlpOrganizationID")]
        public int GlpOrganizationId { get; set; }
        [Key]
        [Column("ClientLookupItemID")]
        public int ClientLookupItemId { get; set; }

        [ForeignKey(nameof(ClientLookupItemId))]
        [InverseProperty(nameof(LookupItem.GlpOrganizationItemTypes))]
        public virtual LookupItem ClientLookupItem { get; set; }
        [ForeignKey(nameof(GlpOrganizationId))]
        [InverseProperty("GlpOrganizationItemTypes")]
        public virtual GlpOrganization GlpOrganization { get; set; }
    }
}