// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("GLPPermission")]
    public partial class Glppermission
    {
        public Glppermission()
        {
            GlppermissionClientUsers = new HashSet<GlppermissionClientUser>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("NameEN")]
        [StringLength(100)]
        public string NameEn { get; set; }
        [Column("NameAR")]
        [StringLength(100)]
        public string NameAr { get; set; }
        [Required]
        [StringLength(100)]
        public string SysName { get; set; }
        [Column("CategoryID")]
        public int CategoryId { get; set; }
        [Column("BatchPermissionID")]
        public int? BatchPermissionId { get; set; }
        [Column("BatchID")]
        public int? BatchId { get; set; }
        [Column("BatchActionTypeID")]
        public int? BatchActionTypeId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }

        [ForeignKey(nameof(BatchId))]
        [InverseProperty("Glppermissions")]
        public virtual Batch Batch { get; set; }
        [InverseProperty(nameof(GlppermissionClientUser.Glppermission))]
        public virtual ICollection<GlppermissionClientUser> GlppermissionClientUsers { get; set; }
    }
}