// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("GLPPermissionClientUser")]
    public partial class GlppermissionClientUser
    {
        [Key]
        [Column("GLPPermission_ID")]
        public int GlppermissionId { get; set; }
        [Key]
        [Column("ClientUser_ID")]
        public int ClientUserId { get; set; }

        [ForeignKey(nameof(ClientUserId))]
        [InverseProperty(nameof(User.GlppermissionClientUsers))]
        public virtual User ClientUser { get; set; }
        [ForeignKey(nameof(GlppermissionId))]
        [InverseProperty("GlppermissionClientUsers")]
        public virtual Glppermission Glppermission { get; set; }
    }
}