// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("Group")]
    public partial class Group
    {
        public Group()
        {
            Meetups = new HashSet<Meetup>();
            ProfileGroups = new HashSet<ProfileGroup>();
            TopicGroups = new HashSet<TopicGroup>();
            Users = new HashSet<User>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("NameEN")]
        [StringLength(50)]
        public string NameEn { get; set; }
        [Column("DescriptionEN")]
        [StringLength(500)]
        public string DescriptionEn { get; set; }
        [Column("CoverImageFileID")]
        public int? CoverImageFileId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column("NameAR")]
        [StringLength(50)]
        public string NameAr { get; set; }
        [Column("DescriptionAR")]
        public string DescriptionAr { get; set; }

        public int? MobCoverImageFileID { get; set; }

        [InverseProperty(nameof(Meetup.Group))]
        public virtual ICollection<Meetup> Meetups { get; set; }
        [InverseProperty(nameof(ProfileGroup.Group))]
        public virtual ICollection<ProfileGroup> ProfileGroups { get; set; }
        [InverseProperty(nameof(TopicGroup.Group))]
        public virtual ICollection<TopicGroup> TopicGroups { get; set; }
        [InverseProperty(nameof(User.Group))]
        public virtual ICollection<User> Users { get; set; }
    }
}