// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("ImpersonationRule", Schema = "bbsf")]
    public partial class ImpersonationRule
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Column("SourceParticipantID")]
        public int SourceParticipantId { get; set; }
        [Column("DestinationParticipantID")]
        public int DestinationParticipantId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ExpiresAt { get; set; }
        public bool IsActive { get; set; }

        [ForeignKey(nameof(DestinationParticipantId))]
        [InverseProperty(nameof(Participant.ImpersonationRuleDestinationParticipants))]
        public virtual Participant DestinationParticipant { get; set; }
        [ForeignKey(nameof(SourceParticipantId))]
        [InverseProperty(nameof(Participant.ImpersonationRuleSourceParticipants))]
        public virtual Participant SourceParticipant { get; set; }
    }
}