// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("InitiativeProfile")]
    public partial class InitiativeProfile
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }

        [Column("ProfileID")]
        public int ProfileId { get; set; }
        [Key]
        [Column("InitiativeID")]
        public int InitiativeId { get; set; }
        [Column("StatusItemID")]
        public int StatusItemId { get; set; }
        [StringLength(500)]
        public string Comment { get; set; }
        public int? ParticipationReferenceID { get; set; }
        public int? StatusID { get; set; }
        public DateTime Created { get; set; }
        public DateTime Modified { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }

        [ForeignKey(nameof(InitiativeId))]
        [InverseProperty("InitiativeProfiles")]
        public virtual Initiative Initiative { get; set; }
        [ForeignKey(nameof(ProfileId))]
        [InverseProperty("InitiativeProfiles")]
        public virtual Profile Profile { get; set; }
        [ForeignKey(nameof(StatusItemId))]
        [InverseProperty(nameof(LookupItem.InitiativeProfiles))]
        public virtual LookupItem StatusItem { get; set; }

        [ForeignKey(nameof(StatusID))]
        [InverseProperty(nameof(LookupItem.InitiativeProfilesStatus))]
        public virtual LookupItem Status { get; set; }

    }
}