// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("InitiativeCategory")]
    public partial class InitiativeCategory
    {
        public InitiativeCategory()
        {
            Initiatives = new HashSet<Initiative>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [Column("TitleEN")]
        [StringLength(100)]
        public string TitleEn { get; set; }
        [Required]
        [Column("DescriptionEN")]
        [StringLength(1000)]
        public string DescriptionEn { get; set; }
        [Column("ImageID")]
        public int? ImageId { get; set; }
        [Column("BannerImageID")]
        public int? BannerImageId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Required]
        [Column("DescriptionAR")]
        [StringLength(1000)]
        public string DescriptionAr { get; set; }
        [Required]
        [Column("TitleAR")]
        [StringLength(100)]
        public string TitleAr { get; set; }

        [InverseProperty(nameof(Initiative.Category))]
        public virtual ICollection<Initiative> Initiatives { get; set; }


//        Invalid column name 'CostAR'.
//Invalid column name 'CostEN'.
//Invalid column name 'DidYouKnowAR'.
//Invalid column name 'DidYouKnowEN'.
//Invalid column name 'EventOrganiserNameEN'.
//Invalid column name 'EventOrganizerEmail'.
//Invalid column name 'EventOrganizerNameAR'.
//Invalid column name 'EventOrganizerPhoneNumber'.
//Invalid column name 'MobImageID'.
//Invalid column name 'PaymentDetailsAR'.
//Invalid column name 'PaymentDetailsEN'.
//Invalid column name 'QRCode'.
//Invalid column name 'ReferenceNumber'.
//Invalid column name 'RegistrationTypeItemID'.
    }
}