// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("KnowledgeHubCategory")]
    public partial class KnowledgeHubCategory
    {
        public KnowledgeHubCategory()
        {
            KnowledgeHubCourses = new HashSet<KnowledgeHubCourse>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Column("TitleEN")]
        public string TitleEn { get; set; }
        [Column("TitleAR")]
        public string TitleAr { get; set; }
        [Column("LogoID")]
        public int LogoId { get; set; }

        [ForeignKey(nameof(LogoId))]
        [InverseProperty(nameof(File.KnowledgeHubCategories))]
        public virtual File Logo { get; set; }
        [InverseProperty(nameof(KnowledgeHubCourse.Category))]
        public virtual ICollection<KnowledgeHubCourse> KnowledgeHubCourses { get; set; }
    }
}