// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Uaeglp.Models.ProfileModels;

namespace Uaeglp.Models
{
    [Table("KnowledgeHubCourse")]
    public partial class KnowledgeHubCourse
    {
        public KnowledgeHubCourse()
        {
            ProfileCourses = new HashSet<ProfileKnowledgeHubCourse>();
        }
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Column("NameEN")]
        public string NameEn { get; set; }
        [Column("NameAR")]
        public string NameAr { get; set; }
        [Column("DescriptionEN")]
        public string DescriptionEn { get; set; }
        [Column("DescriptionAR")]
        public string DescriptionAr { get; set; }
        [Column("AboutEN")]
        public string AboutEn { get; set; }
        [Column("AboutAR")]
        public string AboutAr { get; set; }
        [Column("IframeUrlEN")]
        public string IframeUrlEn { get; set; }
        [Column("IframeUrlAR")]
        public string IframeUrlAr { get; set; }
        public string Language { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? From { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? To { get; set; }
        [Column("ProviderCourseID")]
        public string ProviderCourseId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ProviderLastModifiedDate { get; set; }
        [Column("ImageURL")]
        public string ImageUrl { get; set; }
        public bool ShowProviderIcon { get; set; }
        public bool IsHide { get; set; }
        [Column("CourseTypeID")]
        public int CourseTypeId { get; set; }
        [Column("ProviderTypeID")]
        public int ProviderTypeId { get; set; }
        [Column("CategoryID")]
        public int? CategoryId { get; set; }

        [ForeignKey(nameof(CategoryId))]
        [InverseProperty(nameof(KnowledgeHubCategory.KnowledgeHubCourses))]
        public virtual KnowledgeHubCategory Category { get; set; }
        [ForeignKey(nameof(CourseTypeId))]
        [InverseProperty(nameof(LookupItem.KnowledgeHubCourseCourseTypes))]
        public virtual LookupItem CourseType { get; set; }
        [ForeignKey(nameof(ProviderTypeId))]
        [InverseProperty(nameof(LookupItem.KnowledgeHubCourseProviderTypes))]
        public virtual LookupItem ProviderType { get; set; }

        //[InverseProperty(nameof(ProfileKnowledgeHubCourse.Course))]
        public virtual ICollection<ProfileKnowledgeHubCourse> ProfileCourses { get; set; }
    }
}