// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("Localization")]
    public partial class Localization
    {
        [Key]
        [Column("pk")]
        public int Pk { get; set; }
        [Required]
        [StringLength(1024)]
        public string ResourceId { get; set; }
        public string Value { get; set; }
        [StringLength(10)]
        public string LocaleId { get; set; }
        [StringLength(512)]
        public string ResourceSet { get; set; }
        [StringLength(512)]
        public string Type { get; set; }
        public byte[] BinFile { get; set; }
        public string TextFile { get; set; }
        [StringLength(128)]
        public string Filename { get; set; }
        [StringLength(512)]
        public string Comment { get; set; }
        public int ValueType { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Updated { get; set; }
        public bool IsWentToProduction { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? WentToProductionDate { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
    }
}