// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("Lookup", Schema = "bbsf")]
    public partial class Lookup
    {
        public Lookup()
        {
            LookupItems = new HashSet<LookupItem>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [Column("NameEN")]
        [StringLength(100)]
        public string NameEn { get; set; }
        [Required]
        [Column("NameAR")]
        [StringLength(100)]
        public string NameAr { get; set; }
        [Column("DescriptionEN")]
        [StringLength(250)]
        public string DescriptionEn { get; set; }
        [Column("DescriptionAR")]
        [StringLength(250)]
        public string DescriptionAr { get; set; }
        public bool Manageable { get; set; }
        [Column("LookupGroupID")]
        public int? LookupGroupId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Required]
        [StringLength(100)]
        public string SysName { get; set; }

        [ForeignKey(nameof(LookupGroupId))]
        [InverseProperty("Lookups")]
        public virtual LookupGroup LookupGroup { get; set; }
        [InverseProperty(nameof(LookupItem.Lookup))]
        public virtual ICollection<LookupItem> LookupItems { get; set; }
    }
}