// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("Matrix_Tools")]
    public partial class MatrixTool
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("MatrixID")]
        public int MatrixId { get; set; }
        [Column("AssessmentToolID")]
        public int AssessmentToolId { get; set; }
        public int Weight { get; set; }

        [ForeignKey(nameof(AssessmentToolId))]
        [InverseProperty("MatricesTool")]
        public virtual AssessmentTool AssessmentTool { get; set; }
        [ForeignKey(nameof(MatrixId))]
        [InverseProperty(nameof(AssessmentToolMatrix.MatricesTool))]
        public virtual AssessmentToolMatrix Matrix { get; set; }
    }
}