// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("NetworkGroupProfile")]
    public partial class NetworkGroupProfile
    {
        [Key]
        [Column("NetworkGroup_ID")]
        public int NetworkGroupId { get; set; }
        [Key]
        [Column("Profile_ID")]
        public int ProfileId { get; set; }

        [ForeignKey(nameof(NetworkGroupId))]
        [InverseProperty("NetworkGroupProfiles")]
        public virtual NetworkGroup NetworkGroup { get; set; }
        [ForeignKey(nameof(ProfileId))]
        [InverseProperty("NetworkGroupProfiles")]
        public virtual Profile Profile { get; set; }
    }
}