// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("NetworkGroup")]
    public partial class NetworkGroup
    {
        public NetworkGroup()
        {
            NetworkGroupProfiles = new HashSet<NetworkGroupProfile>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("NameAR")]
        [StringLength(100)]
        public string NameAr { get; set; }
        [Column("NameEN")]
        [StringLength(100)]
        public string NameEn { get; set; }
        [Column("DescriptionEN")]
        public string DescriptionEn { get; set; }
        [Column("DescriptionAR")]
        public string DescriptionAr { get; set; }
        public bool IsActive { get; set; }
        [Column("LogoID")]
        public int? LogoId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }

        [ForeignKey(nameof(LogoId))]
        [InverseProperty(nameof(File.NetworkGroups))]
        public virtual File Logo { get; set; }
        [InverseProperty(nameof(NetworkGroupProfile.NetworkGroup))]
        public virtual ICollection<NetworkGroupProfile> NetworkGroupProfiles { get; set; }
    }
}