// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("ParticipationReference", Schema = "dbo")]
    public partial class ParticipationReference
    {
 
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        public string ReferenceNumber { get; set; }
        public int? ApplicationID { get; set; }
        public int? InitiativeParticipationID { get; set; }
        public int ProfileID { get; set; }
        public int? InitiativeTypeID { get; set; }
        public DateTime Created { get; set; }

        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }

        [ForeignKey(nameof(ProfileID))]
        [InverseProperty("ParticipationReferences")]
        public virtual Profile Profile { get; set; }

        [ForeignKey(nameof(InitiativeParticipationID))]
        public virtual InitiativeProfile InitiativeProfiles { get; set; }

        [ForeignKey(nameof(ApplicationID))]
        public virtual Application Applications { get; set; }

        [ForeignKey(nameof(InitiativeTypeID))]
        public virtual LookupItem LookupItem { get; set; }

    }
}