// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("Permission", Schema = "bbsf")]
    public partial class Permission
    {
        public Permission()
        {
            PermissionSetPermissions = new HashSet<PermissionSetPermission>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("NameEN")]
        [StringLength(100)]
        public string NameEn { get; set; }
        [Column("NameAR")]
        [StringLength(100)]
        public string NameAr { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Required]
        public byte[] RowVersion { get; set; }
        [Column("OrganizationID")]
        public int OrganizationId { get; set; }
        [Required]
        [StringLength(100)]
        public string SysName { get; set; }

        [ForeignKey(nameof(OrganizationId))]
        [InverseProperty("Permissions")]
        public virtual Organization Organization { get; set; }
        [InverseProperty(nameof(PermissionSetPermission.Permission))]
        public virtual ICollection<PermissionSetPermission> PermissionSetPermissions { get; set; }
    }
}