// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("Pillar")]
    public partial class Pillar
    {
        public Pillar()
        {
            Competencies = new HashSet<Competency>();
            PillarAssessmentTools = new HashSet<PillarAssessmentTool>();
            ProfilePillarScores = new HashSet<ProfilePillarScore>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [Column("NameEN")]
        [StringLength(100)]
        public string NameEn { get; set; }
        [Required]
        [Column("NameAR")]
        [StringLength(100)]
        public string NameAr { get; set; }
        [Column("DescriptionEN")]
        [StringLength(300)]
        public string DescriptionEn { get; set; }
        [Column("DescriptionAR")]
        [StringLength(300)]
        public string DescriptionAr { get; set; }
        [Column("ModelID")]
        public int ModelId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }

        [ForeignKey(nameof(ModelId))]
        [InverseProperty(nameof(Glpmodel.Pillars))]
        public virtual Glpmodel Model { get; set; }
        [InverseProperty(nameof(Competency.Pillar))]
        public virtual ICollection<Competency> Competencies { get; set; }
        [InverseProperty(nameof(PillarAssessmentTool.Pillar))]
        public virtual ICollection<PillarAssessmentTool> PillarAssessmentTools { get; set; }
        [InverseProperty(nameof(ProfilePillarScore.Pillar))]
        public virtual ICollection<ProfilePillarScore> ProfilePillarScores { get; set; }
    }
}