// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("Programme")]
    public partial class Programme
    {
        public Programme()
        {
            Batches = new HashSet<Batch>();
            Faqs = new HashSet<Faq>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [Column("TitleEN")]
        [StringLength(300)]
        public string TitleEn { get; set; }
        [Required]
        [Column("TitleAR")]
        [StringLength(300)]
        public string TitleAr { get; set; }
        [Required]
        [Column("DescriptionEN")]
        [StringLength(4000)]
        public string DescriptionEn { get; set; }
        [Required]
        [Column("DescriptionAR")]
        [StringLength(4000)]
        public string DescriptionAr { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        public int Order { get; set; }
        //public decimal? Fees { get; set; }
        //public string Duration { get; set; }
        public bool IsHidden { get; set; }
        [Required]
        [Column("ShortTitleEN")]
        [StringLength(100)]
        public string ShortTitleEn { get; set; }
        [Required]
        [Column("ShortTitleAR")]
        [StringLength(100)]
        public string ShortTitleAr { get; set; }
        [Column("ProgrammeTypeItemID")]
        public int? ProgrammeTypeItemId { get; set; }
      //  public int? ImageId { get; set; }
        [Column("DescriptionHtmlEN")]
        public string DescriptionHtmlEn { get; set; }
        [Column("DescriptionHtmlAR")]
        public string DescriptionHtmlAr { get; set; }

        [Column("SubDescriptionHtmlEN")]
        public string SubDescriptionHtmlEn { get; set; }
        [Column("SubDescriptionHtmlAR")]
        public string SubDescriptionHtmlAr { get; set; }

        [ForeignKey(nameof(ProgrammeTypeItemId))]
        [InverseProperty(nameof(LookupItem.Programmes))]
        public virtual LookupItem ProgrammeTypeItem { get; set; }
        [InverseProperty(nameof(Batch.Programme))]
        public virtual ICollection<Batch> Batches { get; set; }
        [InverseProperty(nameof(Faq.Programme))]
        public virtual ICollection<Faq> Faqs { get; set; }
    }
}