// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("ProviderAttribute", Schema = "bbsf")]
    public partial class ProviderAttribute
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        public int ProviderId { get; set; }
        [Required]
        [StringLength(100)]
        public string Name { get; set; }
        public bool IsEncrypted { get; set; }
        [StringLength(100)]
        public string Value { get; set; }
        public byte[] ValueEncrypted { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Required]
        public byte[] RowVersion { get; set; }

        [ForeignKey(nameof(ProviderId))]
        [InverseProperty("ProviderAttributes")]
        public virtual Provider Provider { get; set; }
    }
}