// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("Provider", Schema = "bbsf")]
    public partial class Provider
    {
        public Provider()
        {
            ProviderAttributes = new HashSet<ProviderAttribute>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("ProviderTypeItemID")]
        public int ProviderTypeItemId { get; set; }
        [StringLength(100)]
        public string Name { get; set; }
        [StringLength(250)]
        public string Description { get; set; }
        [Required]
        [StringLength(256)]
        public string TypeFullName { get; set; }
        public bool IsDefault { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Required]
        public byte[] RowVersion { get; set; }
        [Column("OrganizationID")]
        public int OrganizationId { get; set; }

        [ForeignKey(nameof(OrganizationId))]
        [InverseProperty("Providers")]
        public virtual Organization Organization { get; set; }
        [ForeignKey(nameof(ProviderTypeItemId))]
        [InverseProperty(nameof(LookupItem.Providers))]
        public virtual LookupItem ProviderTypeItem { get; set; }
        [InverseProperty(nameof(ProviderAttribute.Provider))]
        public virtual ICollection<ProviderAttribute> ProviderAttributes { get; set; }
    }
}