// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("PublicHoliday", Schema = "bbsf")]
    public partial class PublicHoliday
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        public string SysName { get; set; }
        [Column("CountryID")]
        public int CountryId { get; set; }
        [Column("ImageFileID")]
        public int? ImageFileId { get; set; }
        public int Day { get; set; }
        public int Month { get; set; }
        [Required]
        [Column("NameEN")]
        [StringLength(100)]
        public string NameEn { get; set; }
        [Required]
        [Column("NameAR")]
        [StringLength(100)]
        public string NameAr { get; set; }
        [Required]
        [Column("DescriptionEN")]
        [StringLength(2000)]
        public string DescriptionEn { get; set; }
        [Required]
        [Column("DescriptionAR")]
        [StringLength(2000)]
        public string DescriptionAr { get; set; }
        public bool IsActive { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }

        [ForeignKey(nameof(CountryId))]
        [InverseProperty("PublicHolidays")]
        public virtual Country Country { get; set; }
        [ForeignKey(nameof(ImageFileId))]
        [InverseProperty(nameof(File.PublicHolidays))]
        public virtual File ImageFile { get; set; }
    }
}