// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("QAnswer")]
    public partial class Qanswer
    {
        public Qanswer()
        {
            ProfileQuestionItemScores = new HashSet<ProfileQuestionItemScore>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [Column("NameEN")]
        public string NameEn { get; set; }
        [Required]
        [Column("NameAR")]
        public string NameAr { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        public bool IsCorrectAnswer { get; set; }
        [Column("QuestionID")]
        public int QuestionId { get; set; }
        public int? Score { get; set; }
        [Column("MobImageID")]
        public int? MobImageID { get; set; }

        [Column("ImageID")]
        public int? ImageId { get; set; }

        [ForeignKey(nameof(ImageId))]
        [InverseProperty(nameof(File.Qanswers))]
        public virtual File Image { get; set; }
        [ForeignKey(nameof(QuestionId))]
        [InverseProperty(nameof(QuestionItem.Qanswers))]
        public virtual QuestionItem Question { get; set; }
        [InverseProperty(nameof(ProfileQuestionItemScore.Answer))]
        public virtual ICollection<ProfileQuestionItemScore> ProfileQuestionItemScores { get; set; }
    }
}