// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("QuestionAnswer")]
    public partial class QuestionAnswer
    {
        public QuestionAnswer()
        {
            Questionansweroptions = new HashSet<QuestionAnswerOption>();
        }
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("ApplicationID")]
        public int? ApplicationId { get; set; }
        [Column("QuestionID")]
        public int QuestionId { get; set; }
        [StringLength(4000)]
        public string Text { get; set; }
        [Column("ProfileID")]
        public int? ProfileId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column("SelectedOptionID")]
        public int? SelectedOptionId { get; set; }
        [Column("YNQuestionAnswer")]
        public bool? YnquestionAnswer { get; set; }
        public int? Scale { get; set; }
        [Column("AnswerFileID")]
        public int? AnswerFileId { get; set; }
        [Column("InitiativeID")]
        public int? InitiativeId { get; set; }
        [Column("SurveyProfileInfoID")]
        public int? SurveyProfileInfoId { get; set; }
        [Column("AssessmentReportFeedbackID")]
        public int? AssessmentReportFeedbackId { get; set; }

        [ForeignKey(nameof(AnswerFileId))]
        [InverseProperty(nameof(File.QuestionAnswers))]
        public virtual File AnswerFile { get; set; }
        [ForeignKey(nameof(ApplicationId))]
        [InverseProperty("QuestionAnswers")]
        public virtual Application Application { get; set; }
        [ForeignKey(nameof(AssessmentReportFeedbackId))]
        [InverseProperty("QuestionAnswers")]
        public virtual AssessmentReportFeedback AssessmentReportFeedback { get; set; }
        [ForeignKey(nameof(InitiativeId))]
        [InverseProperty("QuestionAnswers")]
        public virtual Initiative Initiative { get; set; }
        [ForeignKey(nameof(ProfileId))]
        [InverseProperty("QuestionAnswers")]
        public virtual Profile Profile { get; set; }
        [ForeignKey(nameof(QuestionId))]
        [InverseProperty("QuestionAnswers")]
        public virtual Question Question { get; set; }
        [ForeignKey(nameof(SelectedOptionId))]
        [InverseProperty(nameof(Option.QuestionAnswers))]
        public virtual Option SelectedOption { get; set; }
        [ForeignKey(nameof(SurveyProfileInfoId))]
        [InverseProperty("QuestionAnswers")]
        public virtual SurveyProfileInfo SurveyProfileInfo { get; set; }

       // [InverseProperty(nameof(QuestionAnswerOption.QuestionanswerID))]
        public virtual ICollection<QuestionAnswerOption> Questionansweroptions { get; set; }
    }
}