// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("Question")]
    public partial class Question
    {
        public Question()
        {
            Options = new HashSet<Option>();
            QuestionAnswers = new HashSet<QuestionAnswer>();
            QuestionGroupsQuestions = new HashSet<QuestionGroupsQuestion>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [Column("TextEN")]
        [StringLength(300)]
        public string TextEn { get; set; }
        [Required]
        [Column("TextAR")]
        [StringLength(300)]
        public string TextAr { get; set; }
        [Column("QuestionTypeItemID")]
        public int QuestionTypeItemId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        public int WordCount { get; set; }
        public bool IsPredefined { get; set; }

        [ForeignKey(nameof(QuestionTypeItemId))]
        [InverseProperty(nameof(LookupItem.Questions))]
        public virtual LookupItem QuestionTypeItem { get; set; }
        [InverseProperty(nameof(Option.Question))]
        public virtual ICollection<Option> Options { get; set; }
        [InverseProperty(nameof(QuestionAnswer.Question))]
        public virtual ICollection<QuestionAnswer> QuestionAnswers { get; set; }
        [InverseProperty(nameof(QuestionGroupsQuestion.Question))]
        public virtual ICollection<QuestionGroupsQuestion> QuestionGroupsQuestions { get; set; }
    }
}