// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("QuestionGroup")]
    public partial class QuestionGroup
    {
        public QuestionGroup()
        {
            Batches = new HashSet<Batch>();
            Initiatives = new HashSet<Initiative>();
            QuestionGroupsQuestions = new HashSet<QuestionGroupsQuestion>();
            Surveys = new HashSet<Survey>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [Column("TitleEN")]
        [StringLength(300)]
        public string TitleEn { get; set; }
        [Required]
        [Column("TitleAR")]
        [StringLength(300)]
        public string TitleAr { get; set; }
        [Required]
        [Column("DescriptionEN")]
        [StringLength(300)]
        public string DescriptionEn { get; set; }
        [Required]
        [Column("DescriptionAR")]
        [StringLength(300)]
        public string DescriptionAr { get; set; }
        [Column("DuplicatedFromQuestionGroupID")]
        public int? DuplicatedFromQuestionGroupId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        public bool Manageable { get; set; }

        [InverseProperty(nameof(Batch.QuestionGroup))]
        public virtual ICollection<Batch> Batches { get; set; }
        [InverseProperty(nameof(Initiative.QuestionGroup))]
        public virtual ICollection<Initiative> Initiatives { get; set; }
        [InverseProperty(nameof(QuestionGroupsQuestion.Group))]
        public virtual ICollection<QuestionGroupsQuestion> QuestionGroupsQuestions { get; set; }
        [InverseProperty(nameof(Survey.QuestionGroup))]
        public virtual ICollection<Survey> Surveys { get; set; }
    }
}