// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("QuestionHead")]
    public partial class QuestionHead
    {
        public QuestionHead()
        {
            QuestionItems = new HashSet<QuestionItem>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [Column("NameEN")]
        public string NameEn { get; set; }
        [Required]
        [Column("NameAR")]
        public string NameAr { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column("AssessmentToolID")]
        public int AssessmentToolId { get; set; }
        [Required]
        [Column("TitleEN")]
        [StringLength(100)]
        public string TitleEn { get; set; }
        [Required]
        [Column("TitleAR")]
        [StringLength(100)]
        public string TitleAr { get; set; }
        [Column("AssessmentblockID")]
        public int AssessmentblockId { get; set; }

        [Column("MobImageID")]
        public int? MobImageID { get; set; }

        [Column("ImageID")]
        public int? ImageId { get; set; }

        [ForeignKey(nameof(AssessmentToolId))]
        [InverseProperty("QuestionHeads")]
        public virtual AssessmentTool AssessmentTool { get; set; }
        [ForeignKey(nameof(AssessmentblockId))]
        [InverseProperty(nameof(AssessmentBlock.QuestionHeads))]
        public virtual AssessmentBlock Assessmentblock { get; set; }
        [ForeignKey(nameof(ImageId))]
        [InverseProperty(nameof(File.QuestionHeads))]
        public virtual File Image { get; set; }
        [InverseProperty(nameof(QuestionItem.Questionhead))]
        public virtual ICollection<QuestionItem> QuestionItems { get; set; }
    }
}