// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("Scale")]
    public partial class Scale
    {
        public Scale()
        {
            ProfileScaleScores = new HashSet<ProfileScaleScore>();
            QuestionItems = new HashSet<QuestionItem>();
            SubScales = new HashSet<SubScale>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [Column("NameEN")]
        [StringLength(100)]
        public string NameEn { get; set; }
        [Required]
        [Column("NameAR")]
        [StringLength(100)]
        public string NameAr { get; set; }
        [Column("LowDescriptionEN")]
        public string LowDescriptionEn { get; set; }
        [Column("LowDescriptionAR")]
        public string LowDescriptionAr { get; set; }
        [Column("HighDescriptionEN")]
        public string HighDescriptionEn { get; set; }
        [Column("HighDescriptionAR")]
        public string HighDescriptionAr { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column("FactorID")]
        public int FactorId { get; set; }
        [Column(TypeName = "decimal(20, 10)")]
        public decimal? Mean { get; set; }
        [Column(TypeName = "decimal(20, 10)")]
        public decimal? StandardDeviation { get; set; }
        [Column("NarrativeLowDescriptionEN")]
        public string NarrativeLowDescriptionEn { get; set; }
        [Column("NarrativeLowDescriptionAR")]
        public string NarrativeLowDescriptionAr { get; set; }
        [Column("NarrativeBelowAverageDescriptionEN")]
        public string NarrativeBelowAverageDescriptionEn { get; set; }
        [Column("NarrativeBelowAverageDescriptionAR")]
        public string NarrativeBelowAverageDescriptionAr { get; set; }
        [Column("NarrativeAverageDescriptionEN")]
        public string NarrativeAverageDescriptionEn { get; set; }
        [Column("NarrativeAverageDescriptionAR")]
        public string NarrativeAverageDescriptionAr { get; set; }
        [Column("NarrativeAboveAverageDescriptionEN")]
        public string NarrativeAboveAverageDescriptionEn { get; set; }
        [Column("NarrativeAboveAverageDescriptionAR")]
        public string NarrativeAboveAverageDescriptionAr { get; set; }
        [Column("NarrativeHighDescriptionEN")]
        public string NarrativeHighDescriptionEn { get; set; }
        [Column("NarrativeHighDescriptionAR")]
        public string NarrativeHighDescriptionAr { get; set; }
        [Column("LowestPreferedJobTypesDescriptionEN")]
        public string LowestPreferedJobTypesDescriptionEn { get; set; }
        [Column("LowestPreferedJobTypesDescriptionAR")]
        public string LowestPreferedJobTypesDescriptionAr { get; set; }
        [Column("HighestPreferedJobTypesDescriptionEN")]
        public string HighestPreferedJobTypesDescriptionEn { get; set; }
        [Column("HighestPreferedJobTypesDescriptionAR")]
        public string HighestPreferedJobTypesDescriptionAr { get; set; }

        [ForeignKey(nameof(FactorId))]
        [InverseProperty("Scales")]
        public virtual Factor Factor { get; set; }
        [InverseProperty(nameof(ProfileScaleScore.Scale))]
        public virtual ICollection<ProfileScaleScore> ProfileScaleScores { get; set; }
        [InverseProperty(nameof(QuestionItem.Scale))]
        public virtual ICollection<QuestionItem> QuestionItems { get; set; }
        [InverseProperty(nameof(SubScale.Scale))]
        public virtual ICollection<SubScale> SubScales { get; set; }
    }
}