// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    public partial class ScopeSecret
    {
        [Key]
        public int Id { get; set; }
        [StringLength(1000)]
        public string Description { get; set; }
        public DateTimeOffset? Expiration { get; set; }
        [StringLength(250)]
        public string Type { get; set; }
        [Required]
        [StringLength(250)]
        public string Value { get; set; }
        [Column("Scope_Id")]
        public int ScopeId { get; set; }

        [ForeignKey(nameof(ScopeId))]
        [InverseProperty("ScopeSecrets")]
        public virtual Scope Scope { get; set; }
    }
}