// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    public partial class ScopeClaim
    {
        [Key]
        public int Id { get; set; }
        [Required]
        [StringLength(200)]
        public string Name { get; set; }
        [StringLength(1000)]
        public string Description { get; set; }
        public bool AlwaysIncludeInIdToken { get; set; }
        [Column("Scope_Id")]
        public int ScopeId { get; set; }

        [ForeignKey(nameof(ScopeId))]
        [InverseProperty("ScopeClaims")]
        public virtual Scope Scope { get; set; }
    }
}