// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("ScoringProfile")]
    public partial class ScoringProfile
    {
        [Key]
        [Column("ProfileID")]
        public int ProfileId { get; set; }
        [Column("EducationPHDHolderScore", TypeName = "decimal(18, 2)")]
        public decimal EducationPhdholderScore { get; set; }
        [Column("EducationPHDHolderFromTop200QSRankScore", TypeName = "decimal(18, 2)")]
        public decimal EducationPhdholderFromTop200QsrankScore { get; set; }
        [Column("EducationStudyingPHDScore", TypeName = "decimal(18, 2)")]
        public decimal EducationStudyingPhdscore { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal EducationMasterHolderScore { get; set; }
        [Column("EducationMasterHolderFromTop200QSRankScore", TypeName = "decimal(18, 2)")]
        public decimal EducationMasterHolderFromTop200QsrankScore { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal EducationStudyingMasterScore { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal EducationBachelorScore { get; set; }
        [Column("EducationBachelorFromTop200QSRankScore", TypeName = "decimal(18, 2)")]
        public decimal EducationBachelorFromTop200QsrankScore { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal EducationHigherDiplomaScore { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal EducationDiplomaScore { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal ExperienceInMulinationalOrganizationScore { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal ExperienceInBothPublicAndPrivateScore { get; set; }
        [Column("ExperienceInUAEPrioritySectorScore", TypeName = "decimal(18, 2)")]
        public decimal ExperienceInUaeprioritySectorScore { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal AssessmentPersonalityScore { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal AssessmentEmotionalIntelligenceScore { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal AssessmentWelbeingScore { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Column(TypeName = "decimal(27, 2)")]
        public decimal? EducationTotalScore { get; set; }
        [Column(TypeName = "decimal(20, 2)")]
        public decimal? AssessmentTotalScore { get; set; }
        [Column("Experience1_3YearsScore", TypeName = "decimal(18, 2)")]
        public decimal? Experience13yearsScore { get; set; }
        [Column("Experience4_7YearsScore", TypeName = "decimal(18, 2)")]
        public decimal? Experience47yearsScore { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal? ExperienceAbove7YearsScore { get; set; }
        [Column(TypeName = "decimal(23, 2)")]
        public decimal? WorkExperienceTotalScore { get; set; }
        [Column(TypeName = "decimal(36, 2)")]
        public decimal? ProfileTotalScore { get; set; }

        [ForeignKey(nameof(ProfileId))]
        [InverseProperty("ScoringProfile")]
        public virtual Profile Profile { get; set; }
    }
}