// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("ScoringApplication")]
    public partial class ScoringApplication
    {
        [Key]
        [Column("ApplicationID")]
        public int ApplicationId { get; set; }
        [Column("ProfileID")]
        public int ProfileId { get; set; }
        [Column("ReviewerID")]
        public int ReviewerId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal ProfileTotalScoreAtSelectionTime { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal SpecilaizedInRareJobsScore { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal SelfContributionScore { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal DirectToOrganizationScore { get; set; }
        [Column("ContributedToAProjectOnEmiratesLevelScore", TypeName = "decimal(18, 2)")]
        public decimal ContributedToAprojectOnEmiratesLevelScore { get; set; }
        [Column("ContributedToAProjectOnUAELevelScore", TypeName = "decimal(18, 2)")]
        public decimal ContributedToAprojectOnUaelevelScore { get; set; }
        [Column("ContributedToAProjectOnGlobalLevelScore", TypeName = "decimal(18, 2)")]
        public decimal ContributedToAprojectOnGlobalLevelScore { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal ProgramDetailsScore { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Column("ContributedToASocialActivitiesScore", TypeName = "decimal(18, 2)")]
        public decimal ContributedToAsocialActivitiesScore { get; set; }
        [Column(TypeName = "decimal(25, 2)")]
        public decimal? ApplcationTotalScore { get; set; }

        [ForeignKey(nameof(ApplicationId))]
        [InverseProperty("ScoringApplication")]
        public virtual Application Application { get; set; }
        [ForeignKey(nameof(ProfileId))]
        [InverseProperty("ScoringApplications")]
        public virtual Profile Profile { get; set; }
        [ForeignKey(nameof(ReviewerId))]
        [InverseProperty(nameof(User.ScoringApplications))]
        public virtual User Reviewer { get; set; }
    }
}