// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("SubAssessmentTool")]
    public partial class SubAssessmentTool
    {
        public SubAssessmentTool()
        {
            AssessmentBlocks = new HashSet<AssessmentBlock>();
            ProfileSubAssessmentToolScores = new HashSet<ProfileSubAssessmentToolScore>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [Column("NameEN")]
        [StringLength(100)]
        public string NameEn { get; set; }
        [Required]
        [Column("NameAR")]
        [StringLength(100)]
        public string NameAr { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column("SubAssessmentToolTypeID")]
        public int? SubAssessmentToolTypeId { get; set; }
        [Column("AssessmentToolID")]
        public int AssessmentToolId { get; set; }
        [Column(TypeName = "decimal(20, 10)")]
        public decimal? Mean { get; set; }
        [Column(TypeName = "decimal(20, 10)")]
        public decimal? StandardDeviation { get; set; }

        [ForeignKey(nameof(AssessmentToolId))]
        [InverseProperty("SubAssessmentTools")]
        public virtual AssessmentTool AssessmentTool { get; set; }
        [ForeignKey(nameof(SubAssessmentToolTypeId))]
        [InverseProperty(nameof(LookupItem.SubAssessmentTools))]
        public virtual LookupItem SubAssessmentToolType { get; set; }
        [InverseProperty(nameof(AssessmentBlock.SubAssessmenttool))]
        public virtual ICollection<AssessmentBlock> AssessmentBlocks { get; set; }
        [InverseProperty(nameof(ProfileSubAssessmentToolScore.SubAssessmenttool))]
        public virtual ICollection<ProfileSubAssessmentToolScore> ProfileSubAssessmentToolScores { get; set; }
    }
}