// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("SubScale")]
    public partial class SubScale
    {
        public SubScale()
        {
            CompetencySubscales = new HashSet<CompetencySubscale>();
            ProfileSubScaleScores = new HashSet<ProfileSubScaleScore>();
            QuestionItems = new HashSet<QuestionItem>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [Column("NameEN")]
        [StringLength(100)]
        public string NameEn { get; set; }
        [Required]
        [Column("NameAR")]
        [StringLength(100)]
        public string NameAr { get; set; }
        [Column("LowDescriptionEN")]
        public string LowDescriptionEn { get; set; }
        [Column("LowDescriptionAR")]
        public string LowDescriptionAr { get; set; }
        [Column("HighDescriptionEN")]
        public string HighDescriptionEn { get; set; }
        [Column("HighDescriptionAR")]
        public string HighDescriptionAr { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column("ScaleID")]
        public int ScaleId { get; set; }
        [Column(TypeName = "decimal(20, 10)")]
        public decimal? Mean { get; set; }
        [Column(TypeName = "decimal(20, 10)")]
        public decimal? StandardDeviation { get; set; }

        [ForeignKey(nameof(ScaleId))]
        [InverseProperty("SubScales")]
        public virtual Scale Scale { get; set; }
        [InverseProperty(nameof(CompetencySubscale.Subscale))]
        public virtual ICollection<CompetencySubscale> CompetencySubscales { get; set; }
        [InverseProperty(nameof(ProfileSubScaleScore.SubScale))]
        public virtual ICollection<ProfileSubScaleScore> ProfileSubScaleScores { get; set; }
        [InverseProperty(nameof(QuestionItem.SubScale))]
        public virtual ICollection<QuestionItem> QuestionItems { get; set; }
    }
}