// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("SurveyProfileInfo")]
    public partial class SurveyProfileInfo
    {
        public SurveyProfileInfo()
        {
            QuestionAnswers = new HashSet<QuestionAnswer>();
            SurveyProfileQuestionAnswers = new HashSet<SurveyProfileQuestionAnswer>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("ProfileID")]
        public int? ProfileId { get; set; }
        [Column("SurveyID")]
        public int SurveyId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }

        [ForeignKey(nameof(ProfileId))]
        [InverseProperty("SurveyProfileInfos")]
        public virtual Profile Profile { get; set; }
        [ForeignKey(nameof(SurveyId))]
        [InverseProperty("SurveyProfileInfos")]
        public virtual Survey Survey { get; set; }
        [InverseProperty(nameof(QuestionAnswer.SurveyProfileInfo))]
        public virtual ICollection<QuestionAnswer> QuestionAnswers { get; set; }
        [InverseProperty(nameof(SurveyProfileQuestionAnswer.SurveyProfileInfo))]
        public virtual ICollection<SurveyProfileQuestionAnswer> SurveyProfileQuestionAnswers { get; set; }
    }
}