// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("SurveyProfileQuestionAnswer_SurveyQuestionField")]
    public partial class SurveyProfileQuestionAnswerSurveyQuestionField
    {
        [Key]
        [Column("SurveyProfileQuestionAnswer_ID")]
        public int SurveyProfileQuestionAnswerId { get; set; }
        [Key]
        [Column("SurveyQuestionField_ID")]
        public int SurveyQuestionFieldId { get; set; }

        [ForeignKey(nameof(SurveyProfileQuestionAnswerId))]
        [InverseProperty("SurveyProfileQuestionAnswerSurveyQuestionFields")]
        public virtual SurveyProfileQuestionAnswer SurveyProfileQuestionAnswer { get; set; }
        [ForeignKey(nameof(SurveyQuestionFieldId))]
        [InverseProperty("SurveyProfileQuestionAnswerSurveyQuestionFields")]
        public virtual SurveyQuestionField SurveyQuestionField { get; set; }
    }
}