// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("SurveyQuestion")]
    public partial class SurveyQuestion
    {
        public SurveyQuestion()
        {
            SurveyProfileQuestionAnswers = new HashSet<SurveyProfileQuestionAnswer>();
            SurveyQuestionFieldLinkedSurveyQuestions = new HashSet<SurveyQuestionField>();
            SurveyQuestionFieldSurveyQuestions = new HashSet<SurveyQuestionField>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("SurveyID")]
        public int SurveyId { get; set; }
        [Column("QuestionTypeItemID")]
        public int QuestionTypeItemId { get; set; }
        [Column("QuestionTextEN")]
        [StringLength(500)]
        public string QuestionTextEn { get; set; }
        [Column("QuestionTextAR")]
        [StringLength(500)]
        public string QuestionTextAr { get; set; }
        [Column("PlaceHolderEN")]
        [StringLength(100)]
        public string PlaceHolderEn { get; set; }
        [Column("PlaceHolderAR")]
        [StringLength(100)]
        public string PlaceHolderAr { get; set; }
        public int DisplayOrder { get; set; }
        public bool IsRequired { get; set; }
        public int MaxLength { get; set; }
        public int MaxFileSize { get; set; }
        public string AcceptedFiles { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        public bool IsVisible { get; set; }

        [ForeignKey(nameof(QuestionTypeItemId))]
        [InverseProperty(nameof(LookupItem.SurveyQuestions))]
        public virtual LookupItem QuestionTypeItem { get; set; }
        [ForeignKey(nameof(SurveyId))]
        [InverseProperty("SurveyQuestions")]
        public virtual Survey Survey { get; set; }
        [InverseProperty(nameof(SurveyProfileQuestionAnswer.SurveryQusetion))]
        public virtual ICollection<SurveyProfileQuestionAnswer> SurveyProfileQuestionAnswers { get; set; }
        [InverseProperty(nameof(SurveyQuestionField.LinkedSurveyQuestion))]
        public virtual ICollection<SurveyQuestionField> SurveyQuestionFieldLinkedSurveyQuestions { get; set; }
        [InverseProperty(nameof(SurveyQuestionField.SurveyQuestion))]
        public virtual ICollection<SurveyQuestionField> SurveyQuestionFieldSurveyQuestions { get; set; }
    }
}