// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("Survey")]
    public partial class Survey
    {
        public Survey()
        {
            SurveyProfileInfos = new HashSet<SurveyProfileInfo>();
            SurveyProfileQuestionAnswers = new HashSet<SurveyProfileQuestionAnswer>();
            SurveyQuestions = new HashSet<SurveyQuestion>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("TitleEN")]
        [StringLength(50)]
        public string TitleEn { get; set; }
        [Column("TitleAR")]
        [StringLength(50)]
        public string TitleAr { get; set; }
        [Column("DescriptionEN")]
        public string DescriptionEn { get; set; }
        [Column("DescriptionAR")]
        public string DescriptionAr { get; set; }
        public bool IsPublished { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column("QuestionGroupID")]
        public int? QuestionGroupId { get; set; }

        [ForeignKey(nameof(QuestionGroupId))]
        [InverseProperty("Surveys")]
        public virtual QuestionGroup QuestionGroup { get; set; }
        [InverseProperty(nameof(SurveyProfileInfo.Survey))]
        public virtual ICollection<SurveyProfileInfo> SurveyProfileInfos { get; set; }
        [InverseProperty(nameof(SurveyProfileQuestionAnswer.Survey))]
        public virtual ICollection<SurveyProfileQuestionAnswer> SurveyProfileQuestionAnswers { get; set; }
        [InverseProperty(nameof(SurveyQuestion.Survey))]
        public virtual ICollection<SurveyQuestion> SurveyQuestions { get; set; }
    }
}