// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("SurveyQuestionField")]
    public partial class SurveyQuestionField
    {
        public SurveyQuestionField()
        {
            SurveyProfileQuestionAnswerSurveyQuestionFields = new HashSet<SurveyProfileQuestionAnswerSurveyQuestionField>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("SurveyQuestionID")]
        public int SurveyQuestionId { get; set; }
        [Column("TextEN")]
        public string TextEn { get; set; }
        [Column("TextAR")]
        public string TextAr { get; set; }
        public int DisplayOrder { get; set; }
        [Column("LinkedSurveyQuestionID")]
        public int? LinkedSurveyQuestionId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }

        [ForeignKey(nameof(LinkedSurveyQuestionId))]
        [InverseProperty(nameof(Uaeglp.Models.SurveyQuestion.SurveyQuestionFieldLinkedSurveyQuestions))]
        public virtual SurveyQuestion LinkedSurveyQuestion { get; set; }
        [ForeignKey(nameof(SurveyQuestionId))]
        [InverseProperty("SurveyQuestionFieldSurveyQuestions")]
        public virtual SurveyQuestion SurveyQuestion { get; set; }
        [InverseProperty(nameof(SurveyProfileQuestionAnswerSurveyQuestionField.SurveyQuestionField))]
        public virtual ICollection<SurveyProfileQuestionAnswerSurveyQuestionField> SurveyProfileQuestionAnswerSurveyQuestionFields { get; set; }
    }
}