// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("TemplateUnsubscribe", Schema = "bbsf")]
    public partial class TemplateUnsubscribe
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Column("TemplateID")]
        public int TemplateId { get; set; }
        [Column("UserID")]
        public int UserId { get; set; }
        public bool IsEmail { get; set; }
        public bool IsSms { get; set; }
        [StringLength(500)]
        public string Reason { get; set; }

        [ForeignKey(nameof(TemplateId))]
        [InverseProperty("TemplateUnsubscribes")]
        public virtual Template Template { get; set; }
        [ForeignKey(nameof(UserId))]
        [InverseProperty("TemplateUnsubscribes")]
        public virtual User User { get; set; }
    }
}