// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("Template", Schema = "bbsf")]
    public partial class Template
    {
        public Template()
        {
            Adconnections = new HashSet<Adconnection>();
            TemplateInfos = new HashSet<TemplateInfo>();
            TemplateUnsubscribes = new HashSet<TemplateUnsubscribe>();
            WorkflowActivities = new HashSet<WorkflowActivity>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("CategoryItemID")]
        public int? CategoryItemId { get; set; }
        [Column("NameEN")]
        [StringLength(100)]
        public string NameEn { get; set; }
        [Column("NameAR")]
        [StringLength(100)]
        public string NameAr { get; set; }
        [Column("DescriptionEN")]
        [StringLength(250)]
        public string DescriptionEn { get; set; }
        [Column("DescriptionAR")]
        [StringLength(250)]
        public string DescriptionAr { get; set; }
        public bool IsEmail { get; set; }
        public bool IsSms { get; set; }
        public bool EnableIntensiveLogging { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Required]
        public byte[] RowVersion { get; set; }
        [Column("OrganizationID")]
        public int OrganizationId { get; set; }
        [Required]
        [StringLength(100)]
        public string SysName { get; set; }

        [ForeignKey(nameof(CategoryItemId))]
        [InverseProperty(nameof(LookupItem.Templates))]
        public virtual LookupItem CategoryItem { get; set; }
        [ForeignKey(nameof(OrganizationId))]
        [InverseProperty("Templates")]
        public virtual Organization Organization { get; set; }
        [InverseProperty(nameof(Adconnection.WelcomeTemplate))]
        public virtual ICollection<Adconnection> Adconnections { get; set; }
        [InverseProperty(nameof(TemplateInfo.Template))]
        public virtual ICollection<TemplateInfo> TemplateInfos { get; set; }
        [InverseProperty(nameof(TemplateUnsubscribe.Template))]
        public virtual ICollection<TemplateUnsubscribe> TemplateUnsubscribes { get; set; }
        [InverseProperty(nameof(WorkflowActivity.Template))]
        public virtual ICollection<WorkflowActivity> WorkflowActivities { get; set; }
    }
}