// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("TemplateInfo", Schema = "bbsf")]
    public partial class TemplateInfo
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column("EmailSubjectEN")]
        [StringLength(70)]
        public string EmailSubjectEn { get; set; }
        [Column("EmailSubjectAR")]
        [StringLength(70)]
        public string EmailSubjectAr { get; set; }
        [Column("EmailHtmlBodyTagAttributesEN")]
        public string EmailHtmlBodyTagAttributesEn { get; set; }
        [Column("EmailHtmlBodyTagAttributesAR")]
        public string EmailHtmlBodyTagAttributesAr { get; set; }
        [Column("EmailBodyEN")]
        public string EmailBodyEn { get; set; }
        [Column("EmailBodyAR")]
        public string EmailBodyAr { get; set; }
        [Column("LanguageModeItemID")]
        public int LanguageModeItemId { get; set; }
        [Column("SmsEN")]
        public string SmsEn { get; set; }
        [Column("SmsAR")]
        public string SmsAr { get; set; }
        [Required]
        public byte[] RowVersion { get; set; }
        [Column("TemplateID")]
        public int TemplateId { get; set; }
        [Column("EmailHeaderAndFooterTemplateID")]
        public int? EmailHeaderAndFooterTemplateId { get; set; }
        [Column("EmailHtmlHeadSectionEN")]
        public string EmailHtmlHeadSectionEn { get; set; }
        [Column("EmailHtmlHeadSectionAR")]
        public string EmailHtmlHeadSectionAr { get; set; }
        public bool IsMoveCssInline { get; set; }

        [ForeignKey(nameof(EmailHeaderAndFooterTemplateId))]
        [InverseProperty("TemplateInfos")]
        public virtual EmailHeaderAndFooterTemplate EmailHeaderAndFooterTemplate { get; set; }
        [ForeignKey(nameof(LanguageModeItemId))]
        [InverseProperty(nameof(LookupItem.TemplateInfos))]
        public virtual LookupItem LanguageModeItem { get; set; }
        [ForeignKey(nameof(TemplateId))]
        [InverseProperty("TemplateInfos")]
        public virtual Template Template { get; set; }
    }
}