// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("TMETask", Schema = "bbsf")]
    public partial class Tmetask
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [Column("NameEN")]
        public string NameEn { get; set; }
        [Required]
        [Column("NameAR")]
        public string NameAr { get; set; }
        [Column("DescriptionEN")]
        public string DescriptionEn { get; set; }
        [Column("DescriptionAR")]
        public string DescriptionAr { get; set; }
        [Column("TaskURL")]
        [StringLength(2083)]
        public string TaskUrl { get; set; }
        [StringLength(500)]
        public string TaskComment { get; set; }
        [Column("CorrelationID")]
        public Guid? CorrelationId { get; set; }
        public bool IsAlive { get; set; }
        [Column("TaskTypeItemID")]
        public int TaskTypeItemId { get; set; }
        [Column("WFInstanceTaskID")]
        public int? WfinstanceTaskId { get; set; }
        [Column("TaskStatusItemID")]
        public int TaskStatusItemId { get; set; }
        [Column("TaskOutcomeItemID")]
        public int? TaskOutcomeItemId { get; set; }
        [Column("AssociatedObjectID")]
        public string AssociatedObjectId { get; set; }
        [Column("AssignedToUserID")]
        public int AssignedToUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? CompletionDate { get; set; }
        public short? PercentCompleted { get; set; }
        [Column("CorrelationTypeItemID")]
        public int CorrelationTypeItemId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }

        [ForeignKey(nameof(AssignedToUserId))]
        [InverseProperty(nameof(User.Tmetasks))]
        public virtual User AssignedToUser { get; set; }
        [ForeignKey(nameof(CorrelationTypeItemId))]
        [InverseProperty(nameof(LookupItem.TmetaskCorrelationTypeItems))]
        public virtual LookupItem CorrelationTypeItem { get; set; }
        [ForeignKey(nameof(TaskOutcomeItemId))]
        [InverseProperty(nameof(WorkflowActivityOutcome.Tmetasks))]
        public virtual WorkflowActivityOutcome TaskOutcomeItem { get; set; }
        [ForeignKey(nameof(TaskStatusItemId))]
        [InverseProperty(nameof(LookupItem.TmetaskTaskStatusItems))]
        public virtual LookupItem TaskStatusItem { get; set; }
        [ForeignKey(nameof(WfinstanceTaskId))]
        [InverseProperty(nameof(WorkflowInstanceTask.Tmetasks))]
        public virtual WorkflowInstanceTask WfinstanceTask { get; set; }
    }
}