// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    public partial class Token
    {
        [Key]
        [StringLength(128)]
        public string Key { get; set; }
        [Key]
        public short TokenType { get; set; }
        [StringLength(200)]
        public string SubjectId { get; set; }
        [Required]
        [StringLength(200)]
        public string ClientId { get; set; }
        [Required]
        public string JsonCode { get; set; }
        public DateTimeOffset Expiry { get; set; }
    }
}