// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("TopicGroup")]
    public partial class TopicGroup
    {
        [Key]
        [Column("Topic_ID")]
        public int TopicId { get; set; }
        [Key]
        [Column("Group_ID")]
        public int GroupId { get; set; }

        [ForeignKey(nameof(GroupId))]
        [InverseProperty("TopicGroups")]
        public virtual Group Group { get; set; }
        [ForeignKey(nameof(TopicId))]
        [InverseProperty("TopicGroups")]
        public virtual Topic Topic { get; set; }
    }
}