// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Uaeglp.ViewModels.Enums;

namespace Uaeglp.Models
{
    [Table("UserDeviceInfo", Schema = "app")]
    public  class UserDeviceInfo
    {
        
        [Key]
        public string DeviceId { get; set; }

        [Column("UserID")]
        public int UserId { get; set; }

        public byte DeviceType { get; set; }
    
        public bool IsActive { get; set; }

        [Column(TypeName = "datetime")]
        public DateTime? CreatedOn { get; set; }

        [Column(TypeName = "datetime")]
        public DateTime? ModifiedOn { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty("UserDeviceInfos")]
        public virtual User User { get; set; }


    }
}