// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("UserInfo", Schema = "bbsf")]
    public partial class UserInfo
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("UserID")]
        public int UserId { get; set; }
        [StringLength(255)]
        public string Mobile { get; set; }
        [Required]
        [StringLength(256)]
        public string Email { get; set; }
        [Required]
        [StringLength(75)]
        public string Password { get; set; }
        [Required]
        [StringLength(25)]
        public string Token { get; set; }
        [Column("Token_IsCompleted")]
        public bool TokenIsCompleted { get; set; }
        [Column("Token_CanExpire")]
        public bool TokenCanExpire { get; set; }
        public bool IsActive { get; set; }
        public bool CanLogin { get; set; }
        public bool IsLicensed { get; set; }
        public short FailedLoginCount { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? FailedLoginAttempt { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastLogin { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? LastPasswordChangeDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? ActivationDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? DeactivationDate { get; set; }
        [Required]
        public byte[] RowVersion { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        public int? OTP { get; set; }

        [ForeignKey(nameof(UserId))]
        [InverseProperty("UserInfos")]
        public virtual User User { get; set; }
    }
}