// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    public partial class VidAssesCriterion
    {
        public VidAssesCriterion()
        {
            Criterion1s = new HashSet<Criterion1>();
            ProfileVideoAssessmentCriteriaScores = new HashSet<ProfileVideoAssessmentCriteriaScore>();
            VideoAssessments = new HashSet<VideoAssessment>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Required]
        [Column("NameEN")]
        [StringLength(100)]
        public string NameEn { get; set; }
        [Required]
        [Column("NameAR")]
        [StringLength(100)]
        public string NameAr { get; set; }
        [Column("DescriptionEN")]
        public string DescriptionEn { get; set; }
        [Column("DescriptionAR")]
        public string DescriptionAr { get; set; }
        [Column("CriteriaCalculationTypeID")]
        public int CriteriaCalculationTypeId { get; set; }

        [ForeignKey(nameof(CriteriaCalculationTypeId))]
        [InverseProperty(nameof(LookupItem.VidAssesCriteria))]
        public virtual LookupItem CriteriaCalculationType { get; set; }
        [InverseProperty(nameof(Criterion1.Criteria))]
        public virtual ICollection<Criterion1> Criterion1s { get; set; }
        [InverseProperty(nameof(ProfileVideoAssessmentCriteriaScore.Criteria))]
        public virtual ICollection<ProfileVideoAssessmentCriteriaScore> ProfileVideoAssessmentCriteriaScores { get; set; }
        [InverseProperty(nameof(VideoAssessment.Criteria))]
        public virtual ICollection<VideoAssessment> VideoAssessments { get; set; }
    }
}