// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("VideoAssessmentQuestion")]
    public partial class VideoAssessmentQuestion
    {
        public VideoAssessmentQuestion()
        {
            ProfileVideoAssessmentAnswerScores = new HashSet<ProfileVideoAssessmentAnswerScore>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column("NameEN")]
        public string NameEn { get; set; }
        [Column("NameAR")]
        public string NameAr { get; set; }
        [Column("VideoAssessmentID")]
        public int VideoAssessmentId { get; set; }

        [ForeignKey(nameof(VideoAssessmentId))]
        [InverseProperty("VideoAssessmentQuestions")]
        public virtual VideoAssessment VideoAssessment { get; set; }
        [InverseProperty(nameof(ProfileVideoAssessmentAnswerScore.Question))]
        public virtual ICollection<ProfileVideoAssessmentAnswerScore> ProfileVideoAssessmentAnswerScores { get; set; }
    }
}