// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("Workflow", Schema = "bbsf")]
    public partial class Workflow
    {
        public Workflow()
        {
            WorkflowVersions = new HashSet<WorkflowVersion>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [StringLength(100)]
        public string SysName { get; set; }
        [Required]
        [Column("NameEN")]
        [StringLength(255)]
        public string NameEn { get; set; }
        [Required]
        [Column("NameAR")]
        [StringLength(255)]
        public string NameAr { get; set; }
        [Column("DescriptionEN")]
        [StringLength(1000)]
        public string DescriptionEn { get; set; }
        [Column("DescriptionAR")]
        [StringLength(1000)]
        public string DescriptionAr { get; set; }
        public bool IsActive { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }

        [InverseProperty(nameof(WorkflowVersion.Workflow))]
        public virtual ICollection<WorkflowVersion> WorkflowVersions { get; set; }
    }
}