// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("WorkflowActivityVariable", Schema = "bbsf")]
    public partial class WorkflowActivityVariable
    {
        public WorkflowActivityVariable()
        {
            WorkflowLogVariables = new HashSet<WorkflowLogVariable>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("ActivityID")]
        public int ActivityId { get; set; }
        [Column("VariableID")]
        public int VariableId { get; set; }
        public bool IsMandatory { get; set; }
        public bool IsEnabled { get; set; }
        public bool IsVisible { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }

        [ForeignKey(nameof(ActivityId))]
        [InverseProperty(nameof(WorkflowActivity.WorkflowActivityVariables))]
        public virtual WorkflowActivity Activity { get; set; }
        [ForeignKey(nameof(VariableId))]
        [InverseProperty(nameof(WorkflowVariable.WorkflowActivityVariables))]
        public virtual WorkflowVariable Variable { get; set; }
        [InverseProperty(nameof(WorkflowLogVariable.ActivityVariable))]
        public virtual ICollection<WorkflowLogVariable> WorkflowLogVariables { get; set; }
    }
}