// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("WorkflowLog", Schema = "bbsf")]
    public partial class WorkflowLog
    {
        public WorkflowLog()
        {
            WorkflowLogVariables = new HashSet<WorkflowLogVariable>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("InstanceID")]
        public int InstanceId { get; set; }
        [Column("WorkflowVersionID")]
        public int WorkflowVersionId { get; set; }
        [Column("ActivityID")]
        public int ActivityId { get; set; }
        [Column("ActivityOutcomeID")]
        public int? ActivityOutcomeId { get; set; }
        [Column("CompletedByUserID")]
        public int? CompletedByUserId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime CompletedOn { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }
        [Column("CorrelationID")]
        public Guid? CorrelationId { get; set; }

        [ForeignKey(nameof(ActivityId))]
        [InverseProperty(nameof(WorkflowActivity.WorkflowLogs))]
        public virtual WorkflowActivity Activity { get; set; }
        [ForeignKey(nameof(ActivityOutcomeId))]
        [InverseProperty(nameof(WorkflowActivityOutcome.WorkflowLogs))]
        public virtual WorkflowActivityOutcome ActivityOutcome { get; set; }
        [ForeignKey(nameof(CompletedByUserId))]
        [InverseProperty(nameof(User.WorkflowLogs))]
        public virtual User CompletedByUser { get; set; }
        [ForeignKey(nameof(InstanceId))]
        [InverseProperty(nameof(WorkflowInstance.WorkflowLogs))]
        public virtual WorkflowInstance Instance { get; set; }
        [ForeignKey(nameof(WorkflowVersionId))]
        [InverseProperty("WorkflowLogs")]
        public virtual WorkflowVersion WorkflowVersion { get; set; }
        [InverseProperty(nameof(WorkflowLogVariable.Log))]
        public virtual ICollection<WorkflowLogVariable> WorkflowLogVariables { get; set; }
    }
}