// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("WorkflowVariable", Schema = "bbsf")]
    public partial class WorkflowVariable
    {
        public WorkflowVariable()
        {
            Participants = new HashSet<Participant>();
            WorkflowActivityVariables = new HashSet<WorkflowActivityVariable>();
            WorkflowInstanceVariables = new HashSet<WorkflowInstanceVariable>();
            WorkflowVariableLookups = new HashSet<WorkflowVariableLookup>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [Column("NameEN")]
        [StringLength(255)]
        public string NameEn { get; set; }
        [Required]
        [Column("NameAR")]
        [StringLength(255)]
        public string NameAr { get; set; }
        [Required]
        [StringLength(100)]
        public string SysName { get; set; }
        [Column("WorkflowVersionID")]
        public int WorkflowVersionId { get; set; }
        [Column("DataTypeItemID")]
        public int DataTypeItemId { get; set; }
        [Column("VariableTypeItemID")]
        public int VariableTypeItemId { get; set; }
        public bool IsConstant { get; set; }
        [Column("Value_Number")]
        public double? ValueNumber { get; set; }
        [Column("Value_Boolean")]
        public bool? ValueBoolean { get; set; }
        [Column("Value_Date", TypeName = "datetime")]
        public DateTime? ValueDate { get; set; }
        [Column("Value_VariableLookupID")]
        public int? ValueVariableLookupId { get; set; }
        [Column("Value_Identifier")]
        [StringLength(100)]
        public string ValueIdentifier { get; set; }
        [Column("Value_Text")]
        [StringLength(2500)]
        public string ValueText { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }

        [ForeignKey(nameof(DataTypeItemId))]
        [InverseProperty(nameof(LookupItem.WorkflowVariableDataTypeItems))]
        public virtual LookupItem DataTypeItem { get; set; }
        [ForeignKey(nameof(VariableTypeItemId))]
        [InverseProperty(nameof(LookupItem.WorkflowVariableVariableTypeItems))]
        public virtual LookupItem VariableTypeItem { get; set; }
        [ForeignKey(nameof(WorkflowVersionId))]
        [InverseProperty("WorkflowVariables")]
        public virtual WorkflowVersion WorkflowVersion { get; set; }
        [InverseProperty(nameof(Participant.WorkflowVariable))]
        public virtual ICollection<Participant> Participants { get; set; }
        [InverseProperty(nameof(WorkflowActivityVariable.Variable))]
        public virtual ICollection<WorkflowActivityVariable> WorkflowActivityVariables { get; set; }
        [InverseProperty(nameof(WorkflowInstanceVariable.Variable))]
        public virtual ICollection<WorkflowInstanceVariable> WorkflowInstanceVariables { get; set; }
        [InverseProperty(nameof(WorkflowVariableLookup.Variable))]
        public virtual ICollection<WorkflowVariableLookup> WorkflowVariableLookups { get; set; }
    }
}