// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("WorkflowVersion", Schema = "bbsf")]
    public partial class WorkflowVersion
    {
        public WorkflowVersion()
        {
            WorkflowActivities = new HashSet<WorkflowActivity>();
            WorkflowInstances = new HashSet<WorkflowInstance>();
            WorkflowLogs = new HashSet<WorkflowLog>();
            WorkflowVariables = new HashSet<WorkflowVariable>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("WorkflowID")]
        public int WorkflowId { get; set; }
        [Required]
        [Column("ChangeEN")]
        [StringLength(255)]
        public string ChangeEn { get; set; }
        [Required]
        [Column("ChangeAR")]
        [StringLength(255)]
        public string ChangeAr { get; set; }
        public bool IsCurrent { get; set; }
        public bool IsPublished { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }

        [ForeignKey(nameof(WorkflowId))]
        [InverseProperty("WorkflowVersions")]
        public virtual Workflow Workflow { get; set; }
        [InverseProperty(nameof(WorkflowActivity.WorkflowVersion))]
        public virtual ICollection<WorkflowActivity> WorkflowActivities { get; set; }
        [InverseProperty(nameof(WorkflowInstance.WorkflowVersion))]
        public virtual ICollection<WorkflowInstance> WorkflowInstances { get; set; }
        [InverseProperty(nameof(WorkflowLog.WorkflowVersion))]
        public virtual ICollection<WorkflowLog> WorkflowLogs { get; set; }
        [InverseProperty(nameof(WorkflowVariable.WorkflowVersion))]
        public virtual ICollection<WorkflowVariable> WorkflowVariables { get; set; }
    }
}