// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("WorkflowInstance", Schema = "bbsf")]
    public partial class WorkflowInstance
    {
        public WorkflowInstance()
        {
            WorkflowErrors = new HashSet<WorkflowError>();
            WorkflowInstanceComments = new HashSet<WorkflowInstanceComment>();
            WorkflowInstanceTasks = new HashSet<WorkflowInstanceTask>();
            WorkflowInstanceVariables = new HashSet<WorkflowInstanceVariable>();
            WorkflowLogs = new HashSet<WorkflowLog>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Required]
        [StringLength(255)]
        public string SysName { get; set; }
        [Required]
        [Column("NameEN")]
        [StringLength(255)]
        public string NameEn { get; set; }
        [Required]
        [Column("NameAR")]
        [StringLength(255)]
        public string NameAr { get; set; }
        [Column("WorkflowVersionID")]
        public int WorkflowVersionId { get; set; }
        [Column("CurrentActivityID")]
        public int CurrentActivityId { get; set; }
        [Column("StartedByUserID")]
        public int StartedByUserId { get; set; }
        [Column("InstanceStatusItemID")]
        public int InstanceStatusItemId { get; set; }
        [Required]
        [Column("AssociatedObjectID")]
        [StringLength(255)]
        public string AssociatedObjectId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime StartDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime? EndDate { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }

        [ForeignKey(nameof(CurrentActivityId))]
        [InverseProperty(nameof(WorkflowActivity.WorkflowInstances))]
        public virtual WorkflowActivity CurrentActivity { get; set; }
        [ForeignKey(nameof(InstanceStatusItemId))]
        [InverseProperty(nameof(LookupItem.WorkflowInstances))]
        public virtual LookupItem InstanceStatusItem { get; set; }
        [ForeignKey(nameof(StartedByUserId))]
        [InverseProperty(nameof(User.WorkflowInstances))]
        public virtual User StartedByUser { get; set; }
        [ForeignKey(nameof(WorkflowVersionId))]
        [InverseProperty("WorkflowInstances")]
        public virtual WorkflowVersion WorkflowVersion { get; set; }
        [InverseProperty(nameof(WorkflowError.Instance))]
        public virtual ICollection<WorkflowError> WorkflowErrors { get; set; }
        [InverseProperty(nameof(WorkflowInstanceComment.Instance))]
        public virtual ICollection<WorkflowInstanceComment> WorkflowInstanceComments { get; set; }
        [InverseProperty(nameof(WorkflowInstanceTask.WorkflowInstance))]
        public virtual ICollection<WorkflowInstanceTask> WorkflowInstanceTasks { get; set; }
        [InverseProperty(nameof(WorkflowInstanceVariable.Instance))]
        public virtual ICollection<WorkflowInstanceVariable> WorkflowInstanceVariables { get; set; }
        [InverseProperty(nameof(WorkflowLog.Instance))]
        public virtual ICollection<WorkflowLog> WorkflowLogs { get; set; }
    }
}