// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("WorkflowError", Schema = "bbsf")]
    public partial class WorkflowError
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("InstanceID")]
        public int InstanceId { get; set; }
        [Column("ActivityID")]
        public int ActivityId { get; set; }
        [Required]
        public string Message { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }

        [ForeignKey(nameof(ActivityId))]
        [InverseProperty(nameof(WorkflowActivity.WorkflowErrors))]
        public virtual WorkflowActivity Activity { get; set; }
        [ForeignKey(nameof(InstanceId))]
        [InverseProperty(nameof(WorkflowInstance.WorkflowErrors))]
        public virtual WorkflowInstance Instance { get; set; }
    }
}