// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("WorkflowInstanceVariable", Schema = "bbsf")]
    public partial class WorkflowInstanceVariable
    {
        public WorkflowInstanceVariable()
        {
            WorkflowInstanceVariableVariableLookups = new HashSet<WorkflowInstanceVariableVariableLookup>();
        }

        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("InstanceID")]
        public int InstanceId { get; set; }
        [Column("VariableID")]
        public int VariableId { get; set; }
        [Column("Value_Text")]
        [StringLength(2500)]
        public string ValueText { get; set; }
        [Column("Value_Number")]
        public double? ValueNumber { get; set; }
        [Column("Value_Boolean")]
        public bool? ValueBoolean { get; set; }
        [Column("Value_Date", TypeName = "datetime")]
        public DateTime? ValueDate { get; set; }
        [Column("Value_Guid")]
        public Guid? ValueGuid { get; set; }
        [Column("Value_Identifier")]
        public string ValueIdentifier { get; set; }
        [Column("Value_VariableLookupID")]
        public int? ValueVariableLookupId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }

        [ForeignKey(nameof(InstanceId))]
        [InverseProperty(nameof(WorkflowInstance.WorkflowInstanceVariables))]
        public virtual WorkflowInstance Instance { get; set; }
        [ForeignKey(nameof(VariableId))]
        [InverseProperty(nameof(WorkflowVariable.WorkflowInstanceVariables))]
        public virtual WorkflowVariable Variable { get; set; }
        [InverseProperty(nameof(WorkflowInstanceVariableVariableLookup.VariableLookup))]
        public virtual ICollection<WorkflowInstanceVariableVariableLookup> WorkflowInstanceVariableVariableLookups { get; set; }
    }
}