// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models
{
    [Table("WorkflowLogVariable", Schema = "bbsf")]
    public partial class WorkflowLogVariable
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column("LogID")]
        public int LogId { get; set; }
        [Column("ActivityVariableID")]
        public int ActivityVariableId { get; set; }
        [Column("Value_Text")]
        [StringLength(2500)]
        public string ValueText { get; set; }
        [Column("Value_Number")]
        public double? ValueNumber { get; set; }
        [Column("Value_Boolean")]
        public bool? ValueBoolean { get; set; }
        [Column("Value_Date", TypeName = "datetime")]
        public DateTime? ValueDate { get; set; }
        [Column("Value_Guid")]
        public Guid? ValueGuid { get; set; }
        [Column("Value_VariableLookupID")]
        public long? ValueVariableLookupId { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Required]
        [StringLength(256)]
        public string CreatedBy { get; set; }
        [Required]
        [StringLength(256)]
        public string ModifiedBy { get; set; }

        [ForeignKey(nameof(ActivityVariableId))]
        [InverseProperty(nameof(WorkflowActivityVariable.WorkflowLogVariables))]
        public virtual WorkflowActivityVariable ActivityVariable { get; set; }
        [ForeignKey(nameof(LogId))]
        [InverseProperty(nameof(WorkflowLog.WorkflowLogVariables))]
        public virtual WorkflowLog Log { get; set; }
    }
}