// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.ViewModels
{
    [Table("QuestionAnswer")]
    public partial class QuestionAnswerView
    {
        public int Id { get; set; }
        public string NameEn { get; set; }
        public string NameAr { get; set; }
        public string IDEncrypted { get; set; }
        public bool IsCorrectAnswer { get; set; }
        public int? ApplicationId { get; set; }
        public int QuestionId { get; set; }
        public string Text { get; set; }
        public int? ProfileId { get; set; }
        public DateTime Created { get; set; }
        public DateTime Modified { get; set; }
        public string CreatedBy { get; set; }
        public string ModifiedBy { get; set; }
        public int? SelectedOptionId { get; set; }
        public bool? YnquestionAnswer { get; set; }
        public int? Scale { get; set; }
        public int? AnswerFileId { get; set; }
        public int? InitiativeId { get; set; }
        public int? SurveyProfileInfoId { get; set; }
        public int? AssessmentReportFeedbackId { get; set; }
		public int QuestionTypeItemID { get; set; }
	}
}