// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models.Reports
{
    [Table("ReportSectorsProgramme", Schema = "report")]
    public partial class ReportSectorsProgramme
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        public int Count { get; set; }
        [Column("IndustryID")]
        public int IndustryId { get; set; }
        [Column("IndustryNameEN")]
        public string IndustryNameEn { get; set; }
        [Column("IndustryNameAR")]
        public string IndustryNameAr { get; set; }
        [Column("ProgrammeID")]
        public int ProgrammeId { get; set; }
        [Column("ProgrammeNameEN")]
        public string ProgrammeNameEn { get; set; }
        [Column("ProgrammeNameAR")]
        public string ProgrammeNameAr { get; set; }
    }
}