// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models.Reports
{
    [Table("ReportMeetingHubFollowers", Schema = "report")]
    public partial class ReportMeetingHubFollower
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        public int FollowersCount { get; set; }
        [Column("GroupID")]
        public int GroupId { get; set; }
        [Column("GroupNameEN")]
        public string GroupNameEn { get; set; }
        [Column("GroupNameAR")]
        public string GroupNameAr { get; set; }
    }
}