// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models.Reports
{
    [Table("ReportSectorsEmirate", Schema = "report")]
    public partial class ReportSectorsEmirate
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        public int Count { get; set; }
        [Column("IndustryID")]
        public int IndustryId { get; set; }
        [Column("IndustryNameEN")]
        public string IndustryNameEn { get; set; }
        [Column("IndustryNameAR")]
        public string IndustryNameAr { get; set; }
        [Column("EmirateID")]
        public int EmirateId { get; set; }
        [Column("EmirateNameEN")]
        public string EmirateNameEn { get; set; }
        [Column("EmirateNameAR")]
        public string EmirateNameAr { get; set; }
    }
}