// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models.Reports
{
    [Table("ReportAssessmentPillar", Schema = "report")]
    public partial class ReportAssessmentPillar
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Column("AssessmentID")]
        public int AssessmentId { get; set; }
        [Column("AssessmentNameEN")]
        public string AssessmentNameEn { get; set; }
        [Column("AssessmentNameAR")]
        public string AssessmentNameAr { get; set; }
        [Column("PillarID")]
        public int PillarId { get; set; }
        [Column("PillarEN")]
        public string PillarEn { get; set; }
        [Column("PillarAR")]
        public string PillarAr { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal BestScore { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal AverageScore { get; set; }
    }
}