// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models.Reports
{
    [Table("ReportBatchAcceptance", Schema = "report")]
    public partial class ReportBatchAcceptance
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Column("BatchNameEN")]
        public string BatchNameEn { get; set; }
        [Column("BatchNameAR")]
        public string BatchNameAr { get; set; }
        public int TotalApplicants { get; set; }
        public int TotalAcceptedApplicants { get; set; }
        [Column("BatchID")]
        public int BatchId { get; set; }
    }
}