// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models.Reports
{
    [Table("ReportAssessment_ProfilesWithStatus", Schema = "report")]
    public partial class ReportAssessmentProfilesWithStatus
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        public int InProgressCount { get; set; }
        public int CompletedCount { get; set; }
        [Column("AssessmentToolID")]
        public int AssessmentToolId { get; set; }
        [Column("AssessmentToolNameEN")]
        public string AssessmentToolNameEn { get; set; }
        [Column("AssessmentToolNameAR")]
        public string AssessmentToolNameAr { get; set; }
    }
}