// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models.Reports
{
    [Table("ReportInitiativesCount", Schema = "report")]
    public partial class ReportInitiativesCount
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Column("InititativeID")]
        public int InititativeId { get; set; }
        [Column("InitiativeNameEN")]
        public string InitiativeNameEn { get; set; }
        [Column("InitiativeNameAR")]
        public string InitiativeNameAr { get; set; }
        public int AcceptanceCount { get; set; }
        public int RejectedCount { get; set; }
        public int TotalCount { get; set; }
        public int PendingCount { get; set; }
    }
}