// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models.Reports
{
    [Table("ReportAssessmentPercentageRankingPerBatchMatrix", Schema = "report")]
    public partial class ReportAssessmentPercentageRankingPerBatchMatrix
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Column("BatchID")]
        public int? BatchId { get; set; }
        [Column("BatchNameEN")]
        public string BatchNameEn { get; set; }
        [Column("BatchNameAR")]
        public string BatchNameAr { get; set; }
        public bool IsOverView { get; set; }
        [Column("ProfileID")]
        public int ProfileId { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal ProfilePercentage { get; set; }
        public int Rank { get; set; }
    }
}