// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models.Reports
{
    [Table("ReportSectorRegistrationActivation", Schema = "report")]
    public partial class ReportSectorRegistrationActivation
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        public int PublicRegistrationCount { get; set; }
        public int PrivateRegistrationCount { get; set; }
        public int PrivateActivationCount { get; set; }
        public int TotalRegistartionCount { get; set; }
        public int TotalActivationCount { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Datetime { get; set; }
        public int PublicActivationCount { get; set; }
    }
}