// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models.Reports
{
    [Table("ReportProfileAssessmentRankingTrial", Schema = "report")]
    public partial class ReportProfileAssessmentRankingTrial
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Column("ProfileID")]
        public int ProfileId { get; set; }
        public int Order { get; set; }
        [Column("AssessmenttoolID")]
        public int AssessmenttoolId { get; set; }
        public int Rank { get; set; }
    }
}