// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models.Reports
{
    [Table("ReportTalentSector", Schema = "report")]
    public partial class ReportTalentSector
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Column("SectorID")]
        public int SectorId { get; set; }
        [Column("SectorNameEN")]
        public string SectorNameEn { get; set; }
        [Column("SectorNameAR")]
        public string SectorNameAr { get; set; }
        [Column(TypeName = "decimal(18, 2)")]
        public decimal PercentageCount { get; set; }
        public int TotalRawCount { get; set; }
        public bool IsLocal { get; set; }
    }
}