// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models.Reports
{
    [Table("ReportNetworkEngagement", Schema = "report")]
    public partial class ReportNetworkEngagement
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        public int PostCount { get; set; }
        public int CommentCount { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Datetime { get; set; }
    }
}