// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models.Reports
{
    [Table("ReportProfiles", Schema = "report")]
    public partial class ReportProfile
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        public int ProfilesCount { get; set; }
        public int MaleCount { get; set; }
        public int FemaleCount { get; set; }
        [Column("ENCount")]
        public int Encount { get; set; }
        [Column("ARCount")]
        public int Arcount { get; set; }
        [Column("EmiratesENString")]
        public string EmiratesEnstring { get; set; }
        [Column("EmiratesARString")]
        public string EmiratesArstring { get; set; }
        public int AbuDhabiProfilesCount { get; set; }
        public int DubaiProfilesCount { get; set; }
        public int RasAlKhaimahProfilesCount { get; set; }
        public int SharjahProfilesCount { get; set; }
        public int UmmAlQuwainProfilesCount { get; set; }
        public int AjmanProfilesCount { get; set; }
        public int FujairahProfilesCount { get; set; }
        public int AbuDhabiMalesCount { get; set; }
        public int DubaiMalesCount { get; set; }
        public int RasAlKhaimahMalesCount { get; set; }
        public int SharjahMalesCount { get; set; }
        public int UmmAlQuwainMalesCount { get; set; }
        public int AjmanMalesCount { get; set; }
        public int FujairahMalesCount { get; set; }
        public int AbuDhabiFemalesCount { get; set; }
        public int DubaiFemalesCount { get; set; }
        public int RasAlKhaimahFemalesCount { get; set; }
        public int SharjahFemalesCount { get; set; }
        public int UmmAlQuwainFemalesCount { get; set; }
        public int AjmanFemalesCount { get; set; }
        public int FujairahFemalesCount { get; set; }
        public int AbuDhabiPrivateSectorCount { get; set; }
        public int DubaiPrivateSectorCount { get; set; }
        public int RasAlKhaimahPrivateSectorCount { get; set; }
        public int SharjahPrivateSectorCount { get; set; }
        public int UmmAlQuwainPrivateSectorCount { get; set; }
        public int AjmanPrivateSectorCount { get; set; }
        public int FujairahPrivateSectorCount { get; set; }
        public int AbuDhabiPublicSectorCount { get; set; }
        public int DubaiPublicSectorCount { get; set; }
        public int RasAlKhaimahPublicSectorCount { get; set; }
        public int SharjahPublicSectorCount { get; set; }
        public int UmmAlQuwainPublicSectorCount { get; set; }
        public int AjmanPublicSectorCount { get; set; }
        public int FujairahPublicSectorCount { get; set; }
        [Column("DegreesENString")]
        public string DegreesEnstring { get; set; }
        [Column("DegreesARString")]
        public string DegreesArstring { get; set; }
        public int ExecutiveDirectorsAndAboveCount { get; set; }
        public int SeniorsCount { get; set; }
        public int HigherDiplomasCount { get; set; }
        public int BachelorsCount { get; set; }
        public int MastersCount { get; set; }
        public int DoctoralsCount { get; set; }
        public int ProfessionalCertificationsCount { get; set; }
        public int DiplomasCount { get; set; }
        public int HigherDiplomaMalesCount { get; set; }
        public int BachelorMalesCount { get; set; }
        public int MastersMalesCount { get; set; }
        public int DoctoralMalesCount { get; set; }
        public int ProfessionalCertificationMalesCount { get; set; }
        public int DiplomaMalesCount { get; set; }
        public int HigherDiplomaFemalesCount { get; set; }
        public int BachelorFemalesCount { get; set; }
        public int MastersFemalesCount { get; set; }
        public int DoctoralFemalesCount { get; set; }
        public int ProfessionalCertificationFemalesCount { get; set; }
        public int DiplomaFemalesCount { get; set; }
        public string ProfileProgressCompletion { get; set; }
        [Column("ProfileProgressCompletion0_25Count")]
        public int ProfileProgressCompletion025count { get; set; }
        [Column("ProfileProgressCompletion25_50Count")]
        public int ProfileProgressCompletion2550count { get; set; }
        [Column("ProfileProgressCompletion50_75Count")]
        public int ProfileProgressCompletion5075count { get; set; }
        [Column("ProfileProgressCompletion75_100Count")]
        public int ProfileProgressCompletion75100count { get; set; }
        public string ProfileAges { get; set; }
        [Column("ProfileAge0_25Count")]
        public int ProfileAge025count { get; set; }
        [Column("ProfileAge25_35Count")]
        public int ProfileAge2535count { get; set; }
        [Column("ProfileAge35_45Count")]
        public int ProfileAge3545count { get; set; }
        [Column("ProfileAge45_100Count")]
        public int ProfileAge45100count { get; set; }
        [Column("WithLinkedInURLCount")]
        public int WithLinkedInUrlcount { get; set; }
        [Column("WitTwitterURLCount")]
        public int WitTwitterUrlcount { get; set; }
        public int ActiveProiflesCount { get; set; }
        public int InActiveProiflesCount { get; set; }
    }
}