// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace Uaeglp.Models.Reports
{
    [Table("ReportGovernmentEntitiesCount", Schema = "report")]
    public partial class ReportGovernmentEntitiesCount
    {
        [Key]
        [Column("ID")]
        public int Id { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Created { get; set; }
        [Column(TypeName = "datetime")]
        public DateTime Modified { get; set; }
        [Column("EntityNameEN")]
        public string EntityNameEn { get; set; }
        [Column("EntityNameAR")]
        public string EntityNameAr { get; set; }
        [Column("EntityID")]
        public int EntityId { get; set; }
        public int ActivationCount { get; set; }
        public int RegisteredCount { get; set; }
    }
}