// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore;
using Uaeglp.LangModel;
using Uaeglp.Models;

namespace Uaeglp.Repositories
{
    public partial class FileDbContext : DbContext
    {
        public FileDbContext()
        {
        }

        public FileDbContext(DbContextOptions<FileDbContext> options)
            : base(options)
        {
        }

        public virtual DbSet<FileDB> FileDB { get; set; }
      
        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}